### ISSUE TITLE
HTTP Live Streaming (HDS/HLS) support?

### ISSUE THREAD

**Issue by gaberussell** [polimediaupv/paella#115]
Is there a plan for including support for HDS/HLS support in Paella, possibly by integrating the OSMF framework? RTMP is on track to becoming obsolete as a live-streaming protocol, and it's becoming increasingly hard to find CDNs and streaming providers that support RTMP.

**Comment by djcp** [comment]
IDEALLY at some point this'd be available without a flash fallback. I'm not sure if any of the javascript HLS polyfills perform acceptably yet.

**Comment by ferserc1** [comment]
Currently we are working on HLS support for iOS devices, and we plan to include it in the next version.

**Comment by ferserc1** [comment]
Currently we are working on HLS support for iOS devices, and we plan to include it in the next version.

**Comment by miesgre** [comment]
HLS support is in paella since 4.1.0
Support mpeg-dash will be in paella 5.0
