### ISSUE TITLE
I dont work paella player are you help me

### ISSUE THREAD

**Issue by cemergun** [polimediaupv/paella#130]
my example.html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8;">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Paella Engage Example</title>

    <link rel="stylesheet" href="resources/style/controls.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="resources/style/editor.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="resources/bootstrap/css/bootstrap.slate.min.css" type="text/css" media="screen" charset="utf-8">

    <script type="text/javascript" src="src/base.js"></script>
    <script type="text/javascript" src="javascript/jquery.js"></script>
    <script type="text/javascript" src="src/paella_player.js"></script>
    <script type="text/javascript" src="resources/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="example.js"></script>
  </head>
 	 <body id="body" onload="loadPaella('playerContainer');">
		<div id="playerContainer" style="display:block;width:100%"></div>
	 </body> 
</html>

erorr code screen capture adress

https://plus.google.com/photos/105760647503821477843/albums/6131467233096098801?authkey=CO7H5o775I-a0AE 

I want to run two video stream (presentation.mp4 and presenter.mp4) 

thanks

Cem Ergun
cemergun34@gmail.com

**Comment by leosamu** [comment]
Hi @cemergun checking at your screenshot seems like you did not defined a container for the player in your web, check the docs related to how to configure a standalone paella player http://paellaplayer.upv.es/?page=doc

We are currently working on an easier way to configure a standalone paella. You can check a demo here
http:paellaplayer.upv.es/mediapackagecreator/

Take into consideration that is still in develop stage.

Best regards.
