### ISSUE TITLE
Allow the player to be instantiated in editor mode

### ISSUE THREAD

**Issue by bleedinge** [polimediaupv/paella#131]
Currently, a dirty hack has to be used to directly launch the editor instead of the player.

It would be great if you could create a way in Paella to let it be launched straight to the editor.

For instance, using a parameter in the url:

http://paellaplayer.upv.es/demo/player/index.html?id=belmar-demo&editor=true

**Comment by bleedinge** [comment]
Just pinging you guys. Any chance you can have a look to this?

**Comment by miesgre** [comment]
We plan to separate the editor from the player. So, you can use the editor in other projects.
This feature is planned to be in paella 5.0

**Comment by miesgre** [comment]
Closing this issue as paella 5.0 has no editor. The Paella Editor is now a new project. you can follow the development at https://github.com/polimediaupv/paella-editor
