### ISSUE TITLE
frameControlPlugin not working correctly: hiResFrames aren't removed after hover

### ISSUE THREAD

**Issue by flyapen** [polimediaupv/paella#132]
When using the frameControlPlugin the hiResFrame is shown onMouseOver, this works correctly. Clicking moves the video to the correct timestamp and the videos play correctly but the HiResFrame stays in front of the video. This because onMouseOut has removeHiResFrame commented out.

I changed my local code and removed the comment and this works correctly now, but maybe this code was commented out for another specific reason ?

**Comment by miesgre** [comment]
I don't understand what is the problem, it is working well for me (tested in paellaplayer demo page). Can you send me a URL to test it or Can you grab a video showing me the problem?

Thanks!

**Comment by flyapen** [comment]
I made a short screencapture of this bug, it also shows #94 in the beginning. unfortunately I can't provide you access to our test servers at the moment, but if needed I can see if we can arrange something. I've sent the video to the paella-admin email address.

**Comment by miesgre** [comment]
@flyapen Thanks for the video. I found the bug. We are going to fix it and make a new release. Thanks!
