### ISSUE TITLE
Mute audio is lost when switching to/from fullscreen

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella#133]
When muting the audio, then switching to fullscreen, audio is back on. Same thing the other way round: Muting in fullscreen, then going back to regular size - audio is back on. This is not true for other settings of the audio (very low or very loud), only for (full) mute. Tested with this demo media: http://paellaplayer.upv.es/?page=demo on OS X, Firefox. Greetings from Zurich.

O

**Comment by ferserc1** [comment]
This issue occurs each time the video is reloaded. It's fixed in the development version

**Comment by miesgre** [comment]
Applied patch also to master. Paella 4.0.15 solves this.

**Comment by oas777** [comment]
Please have a look at http://paellaplayer.upv.es/?page=demo (embed demo of what should be 4.1): If muted, the video is unmuted when switching to fullscreen (which happens in a new tab, which it shouldn't). Plus, there's no seamless play, but that's another issue...
