### ISSUE TITLE
MultiQuality Sort order in Safari

### ISSUE THREAD

**Issue by spiraleddy** [polimediaupv/paella#135]
Hi all, Safari doesn't like the boolean returned by the sortFunction in the MultiQualities plugin.The following fix works for Safari, Chrome, FF. Reference by http://stackoverflow.com/questions/7584194/simple-jquery-script-not-working-in-safari. I will try make a pull for this, but feel free to take, test, and add directly, in case I dont. - Thank you for the awesome Player! Best Regards, Karen

-                       return parseInt(a.res.h) >= parseInt(b.res.h);
+                       return (parseInt(a.res.h) >= parseInt(b.res.h)? 1 : -1);

**Comment by miesgre** [comment]
Thanks Karen! I fixed it in paella 4.0.18
