### ISSUE TITLE
MultiQuality selection change with single video fails at volumeRangePlugin storeVolume()

### ISSUE THREAD

**Issue by spiraleddy** [polimediaupv/paella#137]
The storeVolume() tries to store volume on the missing slave [1] . Since the "this._showSlaveVolume" is already false at this point, is it Ok to just add a test like the following?

self._tempSlaveVolume = ((self.__showSlaveVolume)? paella.player.videoContainer.slaveVideo().volume():0);

[1] https://github.com/polimediaupv/paella/blob/master/plugins/es.upv.paella.volumeRangePlugin/volumeRange.js#L59

**Comment by miesgre** [comment]
This was fixed in `develop` [1]. But I moved it to `master` in 4.0.19

https://github.com/polimediaupv/paella/blob/develop/plugins/es.upv.paella.volumeRangePlugin/volumeRange.js#L57-L65
