### ISSUE TITLE
Demo doesn't play live rtmp

### ISSUE THREAD

**Issue by miesgre** [polimediaupv/paella#139]
Issue from @phoebem

We are using an older version of paella and would like to upgrade,
but then I noticed (perhaps I am missing something in the build)
that the flash player is broken for live rtmp for a few releases.

What I did was:
```
git clone from https://github.com/polimediaupv/paella
grunt server.debug
http://localhost:8000/player/index.html?id=a3-tv-live
```
This shows a spinner but the stream never loads, but
```
git checkout 4.0.11
grunt server.debug
http://localhost:8000/player/index.html?id=a3-tv-live
```
This plays as expected.

**Comment by miesgre** [comment]
Paella 4.0.20 should fix this.

**Comment by phoebem** [comment]
Thanks!

Phoebe Miller
Harvard University DCE
