### ISSUE TITLE
FCSubscribe support for live streaming through a CDN

### ISSUE THREAD

**Issue by phoebem** [polimediaupv/paella#140]
Many of the larger CDNs such as akamai, limelight and edgecast require the use of the FCSubscribe/FCUnSubscibe calls to subscribe to a live RTMP stream before it can be played.
Is there any chance you can provide a configurable option to add this functionality?

**Comment by turro** [comment]
Hi Phoebe

Actionscript is quite problematic and we are worrried on breaking something by doing that, so we will prefer just to solve the current problem that you may have than aiming to provide a general solution 

Also we would need a Akamai RTMP stream for testing.

I found this URL talking about that, and we could make some tests if you could provide such a testing place

http://stackoverflow.com/questions/16980799/implementing-fcsubscribe-on-client-side

**Comment by phoebem** [comment]
Hi Turro,

	Thanks so much for looking into this. We don’t have a CDN yet and we are trying to get one before we go live. We don’t want to sign a contract until we know that we have a working video client.

In the past, I have signed up for trial offers from CDNs to set up a live stream for testing.

I will try and set up or find something and send you the link.

Thanks,

Phoebe Miller
Harvard University DCE

**Comment by phoebem** [comment]
Hi Turro,

	Here is an akamai rtmp link:

	rtmp://cp49989.live.edgefcs.net/live/streamRM1@2564

Here is the akamai test player which has a debug trace print out which you may find useful.

http://support.akamai.com/flash/index.html



Phoebe Miller
Harvard University DCE

**Comment by polimediaupv** [comment]
It seems that this bug has nothing to do with the FCSubscribe support: in the javascript side, the URL parser was ignoring the @ character.

I have created a new sample with the akamai rtmp:
    http://localhost:8000/player/index.html?id=life-streaming

**Comment by ferserc1** [comment]
It seems that this bug has nothing to do with the FCSubscribe support: in the javascript side, the URL parser was ignoring the @ character.

I have created a new sample with the akamai rtmp:
http://localhost:8000/player/index.html?id=life-streaming
