### ISSUE TITLE
Resolution switching causes master video to mute and it cannot be unmuted

### ISSUE THREAD

**Issue by djcp** [polimediaupv/paella#142]
To reproduce:

1. Check out paella 4.0.21 (or 4.0.20)
2. `grunt server.debug`
3. Open the multiresolution demo
4. Switch resolutions. The master video will be muted with no way to unmute

This bug isn't visible on http://paellaplayer.upv.es/?page=demo because that's running an earlier version.

**Comment by djcp** [comment]
This happens if you switch resolutions manually or if it's done automatically when going fullscreen.

**Comment by djcp** [comment]
I fixed this in an extremely hackey way here: https://github.com/harvard-dce/paella/commit/8d2b87581659563c7b56623a215242111056f1bb Obviously the real problem is elsewhere.

**Comment by djcp** [comment]
Ignore that fix, I've made a better one via an evented plugin (even though this probably needs to be fixed elsewhere):

```
Class ("paella.plugins.UnmuteVolume",paella.EventDrivenPlugin,{
  getEvents: function() {
    return [paella.events.setVolume];
  },

  onEvent: function(event, params){
    console.log('params: ', params);
    console.log('unmuting volume');
    if (params.master > 0) {
      paella.player.videoContainer.masterVideo().domElement.muted = false;
    }
  },

  checkEnabled: function(onSuccess) {
    onSuccess(dynamic_cast("paella.Html5Video",paella.player.videoContainer.masterVideo())!=null);
  }
});

paella.plugins.unmuteVolume = new paella.plugins.UnmuteVolume();
```

**Comment by miesgre** [comment]
Thanks @djcp, the problem was in the `muted` param added to the video tag.
