### ISSUE TITLE
Live stream volume control shows "muted" by default but audio is not muted

### ISSUE THREAD

**Issue by djcp** [polimediaupv/paella#143]
Hi. When starting a live stream, the volume control UI element shows "muted" even though the audio works.

To replicate:

* Visit http://paellaplayer.upv.es/demo/player/index.html?id=upv-tv-live or http://paellaplayer.upv.es/demo/player/index.html?id=dual-rtmp-live
* See that the volume control is muted even though the audio is on

This bug is the same in the latest release as well.

**Comment by djcp** [comment]
:+1:

**Comment by spiraleddy** [comment]
FYI - We're still seeing the the volume control to mute with our wowza served live streams, even though the live stream loads with audible volume. The 03_video_node.js "volume =  this.flashVideo.getVolume();"   throws an exception because the getVolume() is undefined on the this.flashVideo object. This causes the volume to always return as 0 (instead of the default _volume=1 of the flash streaming object). With the same code and non-Wowza streamed video, the "this.flashVideo.getVolume()" is defined and returns 1 for the volume. 

This issue is not urgent for us because we are moving away from Wowza streaming.

**Comment by miesgre** [comment]
We are now working on the rtmp flash module, so we will have a look at this.
@ferserc1 Please, take note of this.

**Comment by spiraleddy** [comment]
Thank you for looking. The following is an observation from our wowza served live stream flash event params settings in processEvent:function(eventName,params). Notice that our wowza live stream doesn't set a duration and therefore the "this.callReadyEvent()" is not called.

Three consecutive wowza-live stream events. The duration param is always 0.
1st time:
eventName == "play"
params == {"duration":0,"framerate":null,"currentTime":0,"muted":false,"paused":false,"ended":false,"volume":1,"src":"\"\"","bytesTotal":0,"bufferedBytes":0,"bufferedTime":null,"videoWidth":-1,"videoHeight":-1}

2nd time: 
eventName == "loadeddata"
params == {"duration":0,"framerate":30,"currentTime":0,"muted":false,"paused":false,"ended":false,"volume":1,"src":"\"\"","bytesTotal":0,"bufferedBytes":0,"bufferedTime":null,"videoWidth":1920,"videoHeight":540}

3rd time: 
eventName == "canplay"
params == {"duration":0,"framerate":30,"currentTime":0,"muted":false,"paused":false,"ended":false,"volume":1,"src":"\"\"","bytesTotal":0,"bufferedBytes":0,"bufferedTime":null,"videoWidth":1920,"videoHeight":540}

This is a non-Wowza live stream event, it's got a non-zero duration.
event == "loadeddata"
params == "{"duration":596.48,"framerate":24,"currentTime":0,"muted":false,"paused":false,"ended":false,"volume":1,"src":"\"\"","bytesTotal":0,"bufferedBytes":0,"bufferedTime":null,"videoWidth":240,"videoHeight":160}"

Here's the processEvent from 03_video_nodes.js that won't call the callReadyEvent() when params.duration is 0.

	processEvent:function(eventName,params) {
		if (eventName!="loadedmetadata" && eventName!="pause" && params.duration!=0 && !this._isReady) {
			this._isReady = true;
			this._duration = params.duration;
			this.callReadyEvent();
		}
		if (eventName=="progress") {
			try { this.flashVideo.setVolume(this._volume); }
			catch(e) {}
			base.log.debug("Flash video event: " + eventName + ", progress: " + this.flashVideo.currentProgress());
		}
		else {
			base.log.debug("Flash video event: " + eventName);
		}
	},

**Comment by spiraleddy** [comment]
Miguel,

Right now with our live streams, the paella.FlashVideo object never calls it's callReadyEvent(). We started testing a fix to get the duration from the Mediapackage when the duration is not set on the Live Stream by the live streaming server. But, we are concerned of the consequences of  paella.FlashVideo object calling it's callReadyEvent() since everything seems to be working with out it every being called. I'll submit the patch that we were working with for your thoughts, in a moment.

**Comment by spiraleddy** [comment]
We made a local patch make the mute button look unmuted on load. The mute and volume work for the audio of the live stream despite the object staying in a "_ready == false"  the entire time of the live event. 

After researching the behavior of live stream servers, the most common live streaming setting for the duration metada are (1) to omit sending duration param altogether on live events, (2) send the duration as 0 (3) send the duration as -1.

**Comment by miesgre** [comment]
Karen, we have rewritten the flash component for Paella 4.1 and We uploaded that to release/4.1.0 branch.

Can you test if it solves this bug for you? or If you send me a URL to a live streaming to your server I can test it.

**Comment by spiraleddy** [comment]
Miguel, thank you. The fix (https://github.com/polimediaupv/paella/commit/a7350fb71dd2e64128dcd1c885a78104cb0a5081#diff-380dae141451b9865c5654c1b6a804e3) is similar to what we tried (https://github.com/polimediaupv/paella/pull/150/files) so I expect the mute issue will be resolved. We were concerned about what bad thing might happen with isReady = true for live streams, we went with a UI fix to the mute on load as a quick fix. Will 4.1.0 be merged to master, or does it require more testing?

**Comment by miesgre** [comment]
We expect to tag a 4.1.0-RC1 this week (we were waiting for flash component to be rewritten). Now we think it is working correctly and want to release a RC to let people to test it and try to find more bugs.
If we don't found more bugs, we will merge 4.1.0 to master.

**Comment by spiraleddy** [comment]
I can see that the release candidate includes a lot of changes that we would like, I'll get a test rolling if Phoebe hasn't already started. Thank you!

**Comment by miesgre** [comment]
Closing this pull since, issue fixed in a7350fb71dd2e64128dcd1c885a78104cb0a5081
