### ISSUE TITLE
Automated unit and integration testing

### ISSUE THREAD

**Issue by djcp** [polimediaupv/paella#144]
We've invested pretty heavily in paella (thanks for all your hard work on it!) but are getting increasingly uncomfortable with the lack of a javascript-level unit / integration test suite.

We'd love to be able to catch regressions [like the one fixed here](https://github.com/polimediaupv/paella/commit/efcd71a143dfb44b748b844897f0ebd32c066f4e) via an automated test suite. This just isn't the kind of thing we expect to break from a patch-level release and if we had logical tests and code coverage it's far more likely we'd catch it.  When I've worked in well tested codebases, the ability to catch regressions, safely refactor and define what your code is supposed to do in a test has been an invaluable tool.

Shimming tests into an existing project without tests can be difficult, but it's even more difficult if someone outside the core team attempts to do it.

Thoughts? Any plans to build out [karma tests](https://karma-runner.github.io/0.12/index.html) (or whatever framework as long as it's common and easy)?

**Comment by miesgre** [comment]
Good point. I've looked at that and having karma for unit testing and protractor for end-to-end testing. My idea would be to begin with that in the developing of Paella 5, right after the upcoming 4.1 release
