### ISSUE TITLE
Where is the Player folder

### ISSUE THREAD

**Issue by soporteillus** [polimediaupv/paella#163]
Hello everyone, I'm from Chile and my English is quite basic.
I'm trying to install "Paella" on my website and review the documentation in the "easy way" to install says: "You need to copy the player folder to your portal webserver and make it visible at any URL" but I can not find this folder in the downloaded files.
Can anyone help me or guide me please? Thanks

**Comment by miesgre** [comment]
You can find the paella folder under `/build/player`, but You need to build the player first (or download a prebuilt version from bower for example)

Visit https://github.com/polimediaupv/paella/blob/master/doc/download_paella.md for more information about building paella.
