### ISSUE TITLE
Is it Ok for live events to set video container playing to true: _playOnLoad = true?

### ISSUE THREAD

**Issue by spiraleddy** [polimediaupv/paella#164]
Hi,

We're using the usertracking and the playing is always false for live events. The Live event's Flash player callReadyEvent() triggers the "paella.events.singleVideoReady" event that is bound to the "onVideoLoaded()" method. But the "onVideoLoaded()" method won't trigger the "paella.events.play" event, because it's this._playOnLoad defaults to false. 

Is there an easy/proper way to set the this._playOnLoad to true for live events and would setting that true cause issues?

Thank you,
Karen

Related to this, when looking for another way to check for live events playing, the paella.player.playing is true! However, the line #474 in the 09_paella_player.js is not intuitive. See below.

https://github.com/polimediaupv/paella/blob/master/src/09_paella_player.js
Class ("paella.PaellaPlayer", paella.PlayerBase,{
...
	pause:function() {
		this.videoContainer.pause();
	},

	playing:function() {
		return this.paused(); // line #474 <-- ??? 
	},

	paused:function() {
		return this.videoContainer.paused();
	}
...

**Comment by miesgre** [comment]
@ferserc1 Please take a look to this.

**Comment by spiraleddy** [comment]
do you have thoughts about an easy/proper way to set the this._playOnLoad to true for live events? We have it set to false in general, but live events don't pause, we need a way to switch it to true if the event is live.

**Comment by ferserc1** [comment]
The _playOnLoad flag should be set to true always if the source is a live stream. Apart from the fact that the playing() function is wrong, it may be something wrong on the initialization of the FlashVideo object.

I'm going to check it out to see what's happening

**Comment by ferserc1** [comment]
The paella.player.playing() function is fixed in 4.2.0
