### ISSUE TITLE
playbackRatePlugin button does not show in version 4.1.9

### ISSUE THREAD

**Issue by flyapen** [polimediaupv/paella#173]
I'm testing the latest release and everything seems to work except that the playbackRatePlugin does not appear in the list of buttons. The plugin is enabled in the config however. I am testing this in combination with opencast.

**Comment by miesgre** [comment]
Are you testing this with a html5 video or is a flash or streaming video? are you testing it in a mobile device or a desktop?

The playBackRate Plugin only works in HTML5 videos and only in desktop.

**Comment by flyapen** [comment]
I'm testing this for html5 video on a linux desktop with latest firefox and chrome browser

**Comment by miesgre** [comment]
playbackrate is working for me. Can you test http://paellaplayer.upv.es/demo/player_4110/index.html?id=belmar-demo

It is a demo with paella 4.1.10. Is the playbackrate plugin working in that demo?

In your installation:

1.- Check the plugin is enabled in config.json
https://github.com/polimediaupv/paella/blob/master/config/config.json#L46


2.- Check what is going on in the source code
Despite what config.json file say if you are in mobile or using flash, the plugin is not enabled.
Check that by putting a breakpoint or adding a console.log(...) at 
https://github.com/polimediaupv/paella/blob/master/plugins/es.upv.paella.playbackRatePlugin/playback_rate.js#L17-L18

**Comment by flyapen** [comment]
The plugin is enabled in the config.json file, the playbackrate is working in the 4.1.10 demo and it is working in our previous 4.0.x installation.

If I place a breakpoint on that line I can see that enabled is false, calling base.userAgent.browser.IsMobileVersion from the command line console returns false so there must be something in the following condition that makes it trigger a false for enabled.

**Comment by flyapen** [comment]
just installed version 4.1.10 on our test server and I have the same problem there, so it seems to be something specific to our installation

**Comment by miesgre** [comment]
If base.userAgent.browser.IsMobileVersion then paella is loading the video using Flash.

Try this in the console:
```
dynamic_cast("paella.Html5Video",paella.player.videoContainer.masterVideo())

dynamic_cast("paella.FlashVideo",paella.player.videoContainer.masterVideo())
```
If the first line returns an object then the videos is leaded in html5 mode. If the second returns an object then the video is loaded using the flash player.

If videos are loaded using flash, then the playbackrate plugin will not work.

Another way to check this is inspecting the HTML DOM tree. If there is a `<video>` tag or an `<object>` tag.

**Comment by flyapen** [comment]
Should have noticed this, indeed the video is being loaded in flash mode instead of html5 mode. What is strange is that that same video was being loaded in html5 mode in the previous version of paella we had enabled.

**Comment by miesgre** [comment]
Is your paella installation open? Can you provide me a link to a demo video? So, I can test it and try to find out what is happening...

**Comment by flyapen** [comment]
Our test servers are limited in access, so I can't provide access to it right now. I did verify it again to see if the plugin was working in our previous version and in paella 4.0.13 the video loads in html5 mode and not in flash mode. I'll try to find out what has changed and what might be the cause.

**Comment by flyapen** [comment]
The problem is related to the changes to enable live streaming from paella, the source was incorrectly identified as a streaming source, if I disable streaming in the config the video loads in html5 mode again and the playbackrate plugin works as well. I don't know if this is intended behaviour ?

**Comment by miesgre** [comment]
What kind of video are you trying to load?
Can you put a brakpoint at https://github.com/polimediaupv/paella/blob/master/src/04_video_container.js#L836

And check what king of content are you trying to load? mp4? ogg? webm? flv? rtmp? hls?

**Comment by flyapen** [comment]
I'm using paella in combination with opencast, in our mediapackage we have mp4 in the download directory ( loaded over http ) and mp4 that can be streamed via a wowza server ( so an rtmp source ).

The html5 player should load first and in case it's a non html5 enabled browser the flash fallback can occur and the flash player can load the rtmp sources.

**Comment by miesgre** [comment]
Ok,

So, You have a html5 & rtmp sources, then I think I know what is happening

Check your config.json file
https://github.com/polimediaupv/paella/blob/master/config/config.json#L5-L8

the order the methods are in the array is important. The default config is:
```
"methods":[
		   {"name":"streaming","enabled":true},
		   {"name":"html","enabled":true},
		   {"name":"flash","enabled":true},
		   {"name":"image","enabled":true}
],
```

So paella first try lo load the streaming video, if it can be found, streaming is used. if not, paella tries the next one...

so, You have a streaming file (rtmp with wowza). So paella find it and use that source to play the video. RTMP sources are played with the flash component.

**Comment by flyapen** [comment]
ok seems logical, thanks for the help!
