### ISSUE TITLE
paella.PlaybackBar's "divTimeOverlay" over-compensates on trimmed start!

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella#178]
The "divTimeOverlay" start time shows `-1:-1:30` when trimmed start time is 30secs.  The "movePassive" function changes the "time" var twice, once at line #126-129 and again at #138-139.

Removing the second time adjustment at line #138-139, appears to fix the issue.

Class ("paella.PlaybackBar", ...
movePassive:function(event)...

See lines #138-139
https://github.com/polimediaupv/paella/blob/094bf24bcbb0c00520eae28baf2fa26319bf627d/src/06_ui_controls.js#L140

**Comment by miesgre** [comment]
I close this issue as I think it is solved. If not, please reopen it again

**Comment by karendolan** [comment]
Thank you. It looks like it was solved on Jan 15, 2016
https://github.com/polimediaupv/paella/commit/b06421e9cdb50c7da1185619faf5bb76c3482d86
