### ISSUE TITLE
Framelist: time values should be float for more precision

### ISSUE THREAD

**Issue by staubesv** [polimediaupv/paella#188]
Just successfully created the framelist as required for the storyboard to work. It seems, however, the 'time' can only be specified as integer (the player did not show the frames anymore when I wrote floats into the framelist).

Would be great if the time value could be specified as floats for more precision.

**Comment by turro** [comment]
Hmmm, seems more a bug than a feature. We didn't do anything with that time besides adding to currentTime (AFAIK)

I'm going to have a look

**Comment by miesgre** [comment]
Solved in 4acfe4f0ef016c25d3b38992ac9835512d38012f from 4.2.x branch and ec7bd80b2af00900d969f935b7ac65c96aebd603 for 5.0.0
