### ISSUE TITLE
Add autoplay and time URL parameters.

### ISSUE THREAD

**Issue by rubenrua** [polimediaupv/paella#195]
Example of these parameters in other players:

 * https://docs.opencast.org/latest/admin/modules/player.url.parameter/
 * https://developers.google.com/youtube/player_parameters

**Comment by miesgre** [comment]
This is working in paella

Test: https://media.upv.es/player/?id=98effade-26ef-a346-ac43-d06f43b28564&autoplay=true&time=100s

**Comment by rubenrua** [comment]
Oh, great.

I miss a guide/documentation.
