### ISSUE TITLE
Add horizontal bar to the progress bar marking the duration of the frameList pictures

### ISSUE THREAD

**Issue by Alfro** [polimediaupv/paella#196]
Paella can show the 'slides' of a class, it shows them on a list, and it also show the slides when hovering over the progress bar.

We would like it to also have the Opencast feature of showing the 'segments' where this slide is being viewed on the player. I added some picture as examples:

**Opencast 1:**
![oc-1x](https://cloud.githubusercontent.com/assets/11334172/13109150/d485d6ae-d577-11e5-9268-f3f0fa9e5a69.png)

**Opencast 2:**
![oc-2x](https://cloud.githubusercontent.com/assets/11334172/13109152/d90839ce-d577-11e5-8af3-ae325be8f3d5.png)

**Comment by miesgre** [comment]
This feature will be included in the new paella release (5.0)

You can view it in our demo page: http://paellaplayer.upv.es/demo/player_mpegdash/index.html?id=belmar-multiresolution

**Comment by miesgre** [comment]
@Alfro Just inform you that this is also included in release 4.2.0
