### ISSUE TITLE
Mpeg dash plugin with the opencast usertracking plugin

### ISSUE THREAD

**Issue by kristofkeppens** [polimediaupv/paella#208]
When using the mpeg dash implementation together with the opencast usertracking plugin you get errors on sending the usertracking stats because the in and out parameters are set to NaN.

If I add a currentTime function to the mpeg dash plugin the usertracking plugin works as intended but not sure if this is the best solution? The code I added : 

`
currentTime:function() {
        return player.time();
    },
`

**Comment by ferserc1** [comment]
The mpeg-dash plugin will not be supported, because it does not work on iOS devices.
