### ISSUE TITLE
Add support for WebVTT captions

### ISSUE THREAD

**Issue by rubenrua** [polimediaupv/paella#210]
WebVTT is the standard format for the HTML5 [tracks in the media elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track). 

Create a new parser `paella.captions.parsers.DFXPParserPlugin`. JS libraries like [mozilla vtt.js](https://github.com/mozilla/vtt.js) can be useful.

**Comment by rubenrua** [comment]
An idea for a rapid solution can be using VTT captions in the prensenter HTML5 video tag.

**Comment by karendolan** [comment]
It would be very cool for a paella caption plugin to check for existence of captions of WebVTT and fall back to check for captions of DFXP. The same way video formats do a fall back check. Our site has been using DFXP but may mix and match with WebVTT (via references in the Opencast published event Mediapackage elements that are translated into the player).

**Comment by miesgre** [comment]
The way to go is to create a [paella.CaptionParserPlugIn](https://github.com/polimediaupv/paella/blob/master/src/06_1_captions.js#L266-L274), just like  the [DFXP parser](https://github.com/polimediaupv/paella/blob/master/plugins/es.upv.paella.captions.DFXPParserPlugin/dfxp_parser.js).

Paella will load **ALL** captions in the data.json [section](https://github.com/polimediaupv/paella/blob/master/repository_test/repository/pm-be0c7738-039d-9445-8237-8b85f37cd303-remote/data.json#L72-L91) and will parse them using the correct parser (you can mix formats if you want).

**Comment by miesgre** [comment]
Thanks @rubenrua and @bpineiro. Code is now in develop branch

**Comment by rubenrua** [comment]
My fault, the author @brapifra was no @bpineiro.
