### ISSUE TITLE
Feature Request: Play slave video without streaming the master, Play master without streaming slave

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella#211]
Hello, we use the Paella player to stream videos to destinations with tiny network bandwidth. We need a way to easily toggle the master and slave streaming on and off to save bandwidth when the user changes to presenter only or presentation only view. So that when a video is hidden, it can be paused (unsynched) and not streaming and not taking up unnecessary bandwidth. In fact, almost cutting the bandwidth usage in half. 

We are currently doing some gymnastics with the video container by swapping the slave and master config and reloading as a monostream for single presentation view. Then swapping back and reloading as multi stream for dual view. This causes a noticeable delay because the video elements have to be reconstructed with the new source. It would be great if there was an easier way.

"Pause & Mute master" (play and unmute slave) is just a thought, and may not be optimal since a lot of code seems to key off the master element.

Best Regards,
Karen

**Comment by karendolan** [comment]
Story: For iOS and 2 streams, we were required to explicitly stream only one video at a time and to be able to toggle between the presenter (master) and the presentation (slave) video. To accomplish this,  the 2 source video data is preserved in a custom global attribute on page load (1) and a custom control bar plugin "singleVideoToggle" allows the user to toggle out one stream for the other stream (2) .

Our custom singleVideoToggle plugin is very specific and complex, and therefore fragile. We would love you to take a look at it and give us advice on improving it. I would be even better if you create a better version of it for the core Paella player.

Being able to toggle out the number of streaming streams from the originating recording source data will be especially important to us when Paella supports audio only streams as one of the options from the source data.

(1) https://github.com/harvard-dce/paella-matterhorn/commit/1b2d13b1e15e8700086c4723858922da70fc911c#diff-247940768de7e937189f6ec1696ad87bR27
(2) https://github.com/harvard-dce/dce-paella-extensions/blob/master/vendor/plugins/edu.harvard.dce.paella.singleVideoToggle/singleVideoToggle.js

**Comment by karendolan** [comment]
I have updated feature title to be more generic. It was "Pause & Mute Master when hidden behind slave & visa versa to save bandwidth". 

Our site had a workaround in Paella v5.1, to toggle out master-slave video sources, so just the slave sources are the monostream master; then toggle back again to the original master-slave source sets for when the user wants to watch both streams. This was not too hard to do while the player was loaded in Paella v5.1.

But, in Paella 5.2+, the same magic cannot be applied. I cannot determine how to toggle out the master-video sources and reload the videos from the new sources after the page has loaded without causing a lot of confusion in the video wrappers and other items that have links to the videos.

Does the Paella team have ideas about how to stop the master video from streaming while just streaming the slave, or to swap the slave sources in for the master sources and reload the master video after the player has loaded?

**Comment by ferserc1** [comment]
Currently we are making several changes in the paella core related with the video and audio streams to support any number of video streams, and make the operations with streams much more flexible. The first new feature that Paella supports with this new refactoring, is the ability to add any number of audio streams, and change the audio to support multiple languages.

I think that we can add some to the API to support this feature

**Comment by karendolan** [comment]
@ferserc1 It would be great if currently loaded streams could be easily swapped out, again. The ability to do this has been reduced in the latest refactor. To clarify, we are trying to give the user an option to toggle streaming videos in order to play just one slave, without the master or other available slaves from streaming. The goal is to reduce down bandwidth usage. We did this before by swapping out the master source, removing the secondary source, and reloading the videos. This cannot be done in the current release because the plugins seems more bonded to the master video than before.

The only work around I can think of right now is to destroy all player elements, swap out the sources, and completely reload the player, and reset sound level, current time, etc. This is less smooth for the user. Any other suggestions are very welcome.

**Comment by karendolan** [comment]
Hi @ferserc1 I saw the feature was added, then "temporarily" removed. Can you describe  why it needed to be removed? Meanwhile, I'm going to play around with re-adding it to see if I can see why it was removed...

https://github.com/polimediaupv/paella/commit/f761299bd966c985d59803bedeb7c9ae5bbb1992#diff-32c1b41788588bed608dc0cd673c6f37L916

**Comment by karendolan** [comment]
Disabling and Enabling the video worked for the secondary video. We leave the primary (primary audio) always running even when hidden, but it was Ok to "disable" the secondary when hidden. All videos had to be put in paused state when re-enabling the video prior to doing a seek it to synch it to the other(s).  The workaround is too invasive for  pull at this time.
