### ISSUE TITLE
echo issue in opencast 2.2 paella player 

### ISSUE THREAD

**Issue by steven09176** [polimediaupv/paella#212]
There are dual-stream audible in paella player 5.0.9 ，It sound like "echo" 
my opencast version is 2.2.0

**Comment by steven09176** [comment]
please help how can i build it to the jar file， as it did not combine into
paella-matterhorn folder

2016-06-22 15:02 GMT+08:00 Fernando Serrano Carpena <
notifications@github.com>:

> Closed #212 <https://github.com/polimediaupv/paella/issues/212> via
> 98ba35c
> <https://github.com/polimediaupv/paella/commit/98ba35cfbfb390eb0ce2e047cae8536a50dcfcf3>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/polimediaupv/paella/issues/212#event-700060836>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AF2E4XJOjNS1Wq8v-syfNN5Fqo2ILCknks5qON3xgaJpZM4I6sxW>
> .
>



-- 
蕭孟達/Steven Hsiao
Mobile Phone# 0926-109741
靈糧一線領袖培訓學院
網址 : leadership.llcgm.net
地址 : 台北市文山區興隆路四段111號B1
電話 : (02) 2234-7450 轉 15
@@@@ 耶穌愛你 賜你平安 @@@@

**Comment by miesgre** [comment]
The best way to proceed is update you paella-matterhorn project to the 5.0.11 version (5.0.11 tag)
and follow the build instrucitons to build the jar again.

Or you can do it manually:
paella-matterhorn project uses a packages.json file to define which paella version to use
See: https://github.com/polimediaupv/paella-matterhorn/blob/5.0.11/package.json#L11

Then you need to update the dependencies and build the jap package again.
Please follow the build instruction located at: https://github.com/polimediaupv/paella-matterhorn/blob/5.0.11/doc/build.md
