### ISSUE TITLE
How to destroy player or dynamic set data

### ISSUE THREAD

**Issue by babyChou** [polimediaupv/paella#218]
1. I'm trying to remove player and reload it again. How can I remove player in correct way?

following are my code

```
paella.load('playerContainer', { data: data });
setTimeout(function(){
  $('#playerContainer').empty();
  paella.load('playerContainer', { data: dataFormat });
},5000);
```

There are still have error like following image
![image](https://cloud.githubusercontent.com/assets/7037478/18981600/6660ba02-8712-11e6-9cd4-0274ca12b5cc.png)

2.If I want to dynamic set url . What can I do?

**Comment by ferserc1** [comment]
Paella Player 6 cannot be destroyed in this way. For version 7, unload and automatic unload is planned in the roadmap. See the [paella-core 7](https://github.com/polimediaupv/paella-core) repository for more information.
