### ISSUE TITLE
RTMP getCurrentQuality() expects an unexpected source data structure

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella#220]
The RTMP getCurrentQuality() expects this for source qualities ~ sources.image = [q1, q2]
But the rest of paella expects this sort of structure ~  sources['rtmp'] = [q1, q2] 

defer.resolve(this._getQualityObject(this._currentQuality,this._stream.sources.image[this._currentQuality]));
 - versus - 
defer.resolve(this._getQualityObject(this._currentQuality,this._stream.sources[this._streamName][this._currentQuality]));

Our Opencast uses the same stream source format for all it's streams. Should it's rtmp source structure be a different structure than all other types, or is that "image" part of the structure a bug?

Line:
https://github.com/polimediaupv/paella/blob/master/plugins/es.upv.paella.rtmpPlayer/rtmp_player.js#L311

**Comment by miesgre** [comment]
@ferserc1 Can you take a look at this?
Thanks!

**Comment by ferserc1** [comment]
Is fixed in tag 5.0.18
