### ISSUE TITLE
iOS player tries to load mpegdash

### ISSUE THREAD

**Issue by phoebem** [polimediaupv/paella#221]
Hello. 
I found this while trying to play a profile of mpegdash with ios backup on an ipad. Here is a patch I did that seemed to solve the problem.

diff --git a/plugins/es.upv.paella.mpegDashPlayer/mpeg-dash-player.js b/plugins/es.upv.paella.mpegDashPlayer/mpeg-dash-player.js
index fbb752e..cdf05f5 100644
--- a/plugins/es.upv.paella.mpegDashPlayer/mpeg-dash-player.js
+++ b/plugins/es.upv.paella.mpegDashPlayer/mpeg-dash-player.js
@@ -173,14 +173,15 @@ Class ("paella.MpegDashVideo", paella.Html5Video,{
 Class ("paella.videoFactories.MpegDashVideoFactory", {
        isStreamCompatible:function(streamData) {
                try {
-                 if (base.userAgent.system.iOS &&
-                         paella.videoFactories.Html5VideoFactory.s_instances>0)
-                 {
-                         return false;
-                 }
-                 for (var key in streamData.sources) {
-                         if (key=='mpd') return true;
-                 }
+            if (base.userAgent.system.iOS) {
+                if (paella.videoFactories.Html5VideoFactory.s_instances>0 ) 
+                    return false;
+            }
+            else { 
+                    for (var key in streamData.sources) {
+                        if (key=='mpd') return true;
+                    }
+            }

**Comment by karendolan** [comment]
Hi, @phoebem if MpegDash does not work on iOS, at all, can the check for the second instance be removed so it's just

` 
       // Not available for iOS, otherwise check for the mpd
       if (base.userAgent.system.iOS) {
               return false;
       }
       else { 
               for (var key in streamData.sources) {
                   if (key=='mpd') return true;
               }
       }`

**Comment by phoebem** [comment]
Yes, that would work too.

**Comment by ferserc1** [comment]
Fixed in 5.2
