### ISSUE TITLE
Data.json for audio only + slides?

### ISSUE THREAD

**Issue by alejandro-ixiam** [polimediaupv/paella#222]
Hi, we are trying to use Paella player for playing content where:

Main Source: audio .mp3 + speaker image
Slides: jpgs with thumbnail, full view and timestamp

Any hints on how to configure data.json with this setup?

Thanks!!

Alejandro

**Comment by pberthol** [comment]
upvote for this feature

**Comment by ferserc1** [comment]
We've just added this feature to the development branch, which will be released in version 6.1.0.

I've added an example data.json file with audio + slides
