### ISSUE TITLE
Different config.json per display request

### ISSUE THREAD

**Issue by VangelisP** [polimediaupv/paella#224]
Hello.
Is it possible to define a different config.json file per player display?
I noticed on paella_player.js this:

```
/*
 *	playerContainer	Player DOM container id
 *	params.config			Use this configuration file
 *	params.data				Paella video data schema
 *	params.url				Repository URL
 */
paella.load = function(playerContainer, params) 
```

but no matter what I feed the config parameter, it always tries to find the /config/config.json file (and also throws an error).
I tried loading up a json array, which was exact replica of the config.json, didn't work.
I tried loading up only directory structures, didn't work.

Any hint could assist me.

Thank you!

**Comment by ferserc1** [comment]
There's a bug when the configuration file is supplied in the initialization parameters. But the params.config parameters is not an URL, here you must to put the configuration data object.
