### ISSUE TITLE
Speed changes get lost when changing to fullscreen and back

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella#225]
While the icon still says the speed has changed, these changes get lost when you go to fullscreen or back to embed (still can be changed though); cf. http://www.video.ethz.ch/speakers/bernays/2016.html or http://paellaplayer.upv.es/demo/player/index.html?id=belmar-demo.

**Comment by ferserc1** [comment]
That's right, when the video is reloaded, the playback rate is not restored.

I'm going to fix it in the development branch. Thanks!

**Comment by ferserc1** [comment]
Fixed in develop branch
