### ISSUE TITLE
Changes in video layout are stored beyond the current browser session

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella#226]
When I change the video layout for a video, that setup is reactivated after ending and restarting my browser; tested this with Firefox and Chrome on Windows. This seems convenient, but really, it can lead to a situation where you're not even aware there are two videos because a long time ago you decided to view only slides in a video with slides and instructor's recording. Cf. http://www.video.ethz.ch/lectures/d-itet/2016/autumn/227-0689-00L/7afdd011-4ca4-3f83-b28e-ec875fd46943.html?autoplay=true.

**Comment by ferserc1** [comment]
I think you are right.

I'm going to change this behavior: the profile will only be saved if you select a dual stream profile.

**Comment by ferserc1** [comment]
Fixed in develop branch
