### ISSUE TITLE
2 RTMP live will cause error some time

### ISSUE THREAD

**Issue by babyChou** [polimediaupv/paella#227]
When I play 2 rtmp live stream and try to change video layout.
It will cause error some time(only can play one of stream) and I reload the page it still has same error.
but if I open another page play in video mode and change video layout
and open live page again it works!!!

I turn on chrome develop tool the console show
Uncaught TypeError: This.flashVideo.duration is not a function

I know is my data.json set wrong cause error or not?
Here is my data.json 

```
{
	"metadata": {
		"duration": 0,
		"title": "UPV-TV"
	},
	"streams": [
		{
			"sources": {
				"rtmp": [
					{
						"mimetype": "video/mp4",
						"src":{
							"server": "rtmp://10.1.9.82:1935/live",
							"stream": "myStream",
							"requiresSubscription": true
						},
						"res": {
							"w": "1280",
							"h": "720"
						},
						"isLiveStream": true
					}
				]
			},
			"preview": null
		},
		{
			"sources": {
				"rtmp": [
					{
						"mimetype": "video/mp4",
						"src":{
							"server": "rtmp://10.1.9.82:1935/live",
							"stream": "myStream",
							"requiresSubscription": true
						},
						"res": {
							"w": "1280",
							"h": "720"
						},
						"isLiveStream": true
					}
				]
			},
			"preview": null
		}
	]
}
```

**Comment by miesgre** [comment]
I can not reproduce it in Paella 5.2.
