### ISSUE TITLE
Redesign of slide preview on timeline

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella#231]
The current solution
- is too small to be readable (cf. http://www.video.ethz.ch/speakers/lecture.html and attachment), especially in embed mode,
- interfers with display of time (cf. attachment),
- and is not customizable.
![slide_preview_pp](https://cloud.githubusercontent.com/assets/1752342/22823340/6b2d0228-ef83-11e6-91e6-6a9f3be82383.png)

**Comment by ferserc1** [comment]
This issue is fixed in the development branch. Anyway, it's possible to adjust the minimum size of the slide preview modifying the stylesheets:

`
    .divTimeImageOverlay {
        min-width: 256px;
    }
`
