### ISSUE TITLE
Volume plugin slider initialization

### ISSUE THREAD

**Issue by ferserc1** [polimediaupv/paella#238]
The slider in the volume plugin always starts at 50%, instead of loading the correct volume level from the video.

**Comment by karendolan** [comment]
Is this a potential fix?

Change:
			rangeInputMaster.value = this.getMasterVolume(); 
To:
                    this.getMasterVolume().then(function(vol) {
			  rangeInputMaster.value = vol;
                    }

**Comment by ferserc1** [comment]
This issue is related with the migration from Paella 4 to 5. I don't understand how anyone haven't seen it before.

I'm going to review all the source of that plugin, because in a quick view I have seen some things that appear to be wrong.

**Comment by ferserc1** [comment]
Fixed in 5.1.8
