### ISSUE TITLE
Trimmed video with a break begins after the break

### ISSUE THREAD

**Issue by iriadp** [polimediaupv/paella#256]
Steps to reproduce it:

- Trim a video (mainly changing the beginning time for example at 0:30).
- Add a break (e.g. from 2:00 to 2:30)
- Reproduce it.

Error: The timeline is shown complete. The video begins to reproduce after the break, in this example at 2:30.

Tested with Paella 5.1.12

**Comment by ferserc1** [comment]
fixed in 5.1.12
