### ISSUE TITLE
Don't depend on traceur-compiler.js at runtime

### ISSUE THREAD

**Issue by staubesv** [polimediaupv/paella#277]
Paella 5.2.1 only works when traceur-compiler.js is included in means of...

`<script type="text/javascript" src="javascript/traceur-compiler.js"></script>`

Besides not being documented, it is a very, very bad idea to include a 1.4MB javascript library in almost any imaginable case ;-)

The reason why traceur-compiler.js needs to be included is that it also contains the traceur runtime which is needed by the generated ECMAScript Edition 5 code to emulate ES6 at runtime.

Fortunately, there is a standalone traceur-runtime.js with a smaller footprint (140KB) which is a more realistic size.

I will file a pull request adding traceur-runtime.js, adapting the HTMLs and the documentation soon.

**Comment by ferserc1** [comment]
Fixed in develop branch
