### ISSUE TITLE
Typo/Unused code: initialCurrentTipe vs Time in 03_video_nodes

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella#290]
Typo/Unused code in 03_video_nodes, chroma-player, video360 in the onProgress(): "_initialCurrentTipe" vs _initialCurrentTime. I cannot found where that might be set for this object. 

`
		function onProgress(event) {
			if (!This._ready && This.video.readyState==4) {
				This._ready = true;
				if (This._initialCurrentTipe!==undefined) {
					This.video.currentTime = This._initialCurrentTime;
					delete This._initialCurrentTime;
				}
				This._callReadyEvent();
			}
		}
`

**Comment by karendolan** [comment]
I notice that _initialCurrentTipe/_initialCurrentTime block is removed from the video360.js. The desired initial current time is set in an other area, via trimming and the special "start" "end" url params. We have a Use Case to save the current play time of an event in the browser storage/cookie and retrieve it when the same video is loaded at a later date, to start playing at the same timepoint as was last used.

Does it make sense to re-purpose the unused _initialCurrentTime param for that Use Case?

**Comment by ferserc1** [comment]
This issue is related to the prototype 360 video plugin, which was replaced by the canvas plugin system.
