### ISSUE TITLE
Captions with two lines get cut from below when the controls bar hides

### ISSUE THREAD

**Issue by iriadp** [polimediaupv/paella#297]
## Steps to reproduce:
1. Go to Paella Player captions video example.
2. Inspect it and change the resolution to one below 600 px width.
3. Reproduce it and wait until the controls bar hides.
 
## Actual Behavior:
 Most of the captions appear in two lines and the second line appears cut from below.
 
## Expected Behavior:
 It should show the second line complete.
With only one line it does not occur.

**Comment by rubenrua** [comment]
I will work on this tomorrow.
