### ISSUE TITLE
Full screen mode on an ipad doesn't show video's captions

### ISSUE THREAD

**Issue by iriadp** [polimediaupv/paella#303]
## Steps to reproduce:
1. Add captions to a video.
2. Access to it on an ipad and enable the captions.
3. Enable full screen mode.
 
## Actual Behavior:
Captions at full screen mode don't appear. 
 
## Expected Behavior:
 They should appear too at full screen.

**Comment by ferserc1** [comment]
Fixed on iPadOS 13
