### ISSUE TITLE
Feature request: Piwik Support

### ISSUE THREAD

**Issue by hsssystems** [polimediaupv/paella#307]
Hi,

many adopters of OpenCAST are using Piwik for tracking. However, paella doesn't seem to support Piwik up to now. 

Would it be easily possible to implement a 

paella.userTracking.SaverPlugIn

based on the googleAnalytics plugin?

https://github.com/polimediaupv/paella/blob/master/doc/adopter_doc/plugins/es.upv.paella.usertracking.googleAnalyticsSaverPlugin.md

Theodul player supports Piwik and it may be possible to convert the googleAnalytics plugin to 
to a Piwik plugin based on the Piwik implementations of Theodul

https://docs.opencast.org/develop/admin/modules/player.piwik.tracking/

best regards

Harald

**Comment by turro** [comment]
Probably this code will be relevant to that integration
https://bitbucket.org/opencast-community/opencast/src/49d202a46c46e5cd3dea54c755d8a9d477c123c1/modules/matterhorn-engage-theodul-plugin-custom-piwik/src/main/resources/static/main.js

**Comment by miesgre** [comment]
Piwik support added to develop branch. Until the develop branch is stable, it has ported to paella-opencast bundle.
