### ISSUE TITLE
Not force jQuery cache parameter

### ISSUE THREAD

**Issue by rubenrua** [polimediaupv/paella#327]
Use HTTP cache is impossible with the current code of paella player. The jQuery configuration in `base.js` disables the possibility of use it appending `"_={timestamp}"` to the GET parameters.

## Steps to reproduce:
1. View a video in paella.
 
## Actual Behavior:
 
AJAX calls with random `_` parameter: 
```
paella/player/config/config.json?_=1520609085806
paella/player/localization/paella_en.json?_=1520609250171
paella/player/config/profiles/profiles.json?_=1520609242914
```
 
## Expected Behavior:
 AJAX calls without random `_` parameter:: 
```
paella/player/config/config.json
paella/player/localization/paella_en.json
paella/player/config/profiles/profiles.json
```

 
## Workaround (if any):
No workaround possible. Force the cache in each request call has more priority that use  `ajaxSetup`

```
$.ajaxSetup({
  cache: true
});
```

Documentation: http://api.jquery.com/jquery.ajax/
```
cache (default: true, false for dataType 'script' and 'jsonp')
Type: Boolean
If set to false, it will force requested pages not to be cached by the browser. Note: Setting cache to false will only work correctly with HEAD and GET requests. It works by appending "_={timestamp}" to the GET parameters. The parameter is not needed for other types of requests, except in IE8 when a POST is made to a URL that has already been requested by a GET.

```

Code: https://github.com/polimediaupv/paella/blob/master/javascript/base.js#L1036
```
var ajaxObj = jQuery.ajax({
	url:params.url,
	data:params.params,
	cache:false,
	type:type
});
```

**Comment by miesgre** [comment]
Fixed in a6705ad99d7d25ebbf8891002f93c81d87ac0fd3
