### ISSUE TITLE
Layouts selector doesn't show complete using mobile devices.

### ISSUE THREAD

**Issue by iriadp** [polimediaupv/paella#333]
## Steps to reproduce:
1.  Access http://paellaplayer.upv.es/index.html using a mobile device.
2. Play the demo video with the mobile device using the landscape position.
3. Press the layout selector button to change the layout.
 
## Actual Behavior:
 The first item of the layout list gets cut.
 
## Expected Behavior:
 All these items should be shown completely considering the size of the player for each device.
 
![screenshot_20180425-094439](https://user-images.githubusercontent.com/22480039/39235694-e8299730-4876-11e8-8be9-8efca5a95822.png)

**Comment by ferserc1** [comment]
This problem is solved with the new system of active layouts, which significantly reduces the number of layouts in the menu, since the layouts are configurable.
