### ISSUE TITLE
Slide marks in timeline disappear in fullscreen mode

### ISSUE THREAD

**Issue by dpeite** [polimediaupv/paella#339]
## Steps to reproduce:
1. Access http://paellaplayer.upv.es/index.html
2. Play the demo video and activate fullscreen mode
 
## Actual Behavior:
When the video is in fullscreen mode, some slide marks in the timeline disappear
![captura de pantalla de 2018-06-01 10-31-35](https://user-images.githubusercontent.com/19955961/40830797-9a02d322-6587-11e8-88d5-d9e8f4434adb.png)

## Expected Behavior:
The slide marks in the timeline should be the same in both modes
 ![captura de pantalla de 2018-06-01 10-31-03](https://user-images.githubusercontent.com/19955961/40830796-99e15f58-6587-11e8-84de-5bdc425907c7.png)

**Comment by dpeite** [comment]
The problem is in the width of the canvas in the class `playerContainer_controls_playback_playbackBar_canvas` It doesn't change when fullscreen mode.

**Comment by rubenrua** [comment]
Pull request for master in #349

Please merge into `release/6.0.0`
