### ISSUE TITLE
Question about Chrome autoplay policy and forcing playback from script

### ISSUE THREAD

**Issue by dpeite** [polimediaupv/paella#341]
Hi, I have a question regarding to the new Chrome autoplay policy.

If I force Paella Player to play videos from a javascript whitout an user input in Chrome 66 it could fail, depending on Chrome Media Engagement Index (MEI). 

`Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD`

I tried to catch this error in my script, and for example play the video muted when the error occur.

I tried this but the error seems to appear inside Paella and I can't catch it in my script.

```javascript
paella.player.play().catch(function(err){
    console.log("Error in play action")
});
```

In this case, even if the play call fails, the promise resolve correctly and it's not possible to detect the error. Moreover I think this could happend in other scenarios to other actions like pause, setVolume, duration,...

**Comment by rubenrua** [comment]
See https://github.com/polimediaupv/paella/commit/49138f2bb094d5d0c5389a96409aabb2704c4c66

**Comment by rubenrua** [comment]
Pull request for master in #350

In the release/6.0.0 is already ok.
