### ISSUE TITLE
Framecontrol plugin: Problem with current slide and trimmed videos 

### ISSUE THREAD

**Issue by dpeite** [polimediaupv/paella#342]
## Steps to reproduce:
1. Trim a video at the beginning with a trimming start point higher than the time between two slides. To test it I used the video in the repository named jordan-blackboard-remote, TrimmingStart=300 and TrimmingEnd(4000)
2. Navigate by slides
3. Click, for example in the last slide
 
## Actual Behavior:
When you click in the last slide, the video seek to that position. But the current slide selected in the plugin is the previous slide to the clicked one.
![sin nombre](https://user-images.githubusercontent.com/19955961/40839480-115916d2-65a3-11e8-9b85-dd7d10118404.png)

 
## Expected Behavior:
The current slide should be the same that we clicked.

**Comment by ferserc1** [comment]
Fixed in 4af52538462bb0ece7ac691776ba433700a5aeae and 66ebce0344a6333faeabe18bfc5e3c145c322432.

This bug didn't happen in the 6.0.x branch
