### ISSUE TITLE
Zoom and ElasticSearch plugins not addressing paused() promise

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella#348]
## Steps to reproduce:
1. Grep the code for "!paella.player.videoContainer.paused()" or "if(paella.player.paused())"

## Actual Behavior: 
A couple instances are found (in the ES plugin & Zoom plugin)
https://github.com/polimediaupv/paella/blob/c5809367e0a66db1715c60ddf1962dcdbe86981b/plugins/es.upv.paella.usertracking.elasticsearchSaverPlugin/elasticsearchSaverPlugin.js#L31

https://github.com/polimediaupv/paella/blob/master/plugins/es.upv.paella.zoomPlugin/zp.js#L411-L415
  
## Expected Behavior: 
No instances are found. Both calls return a promise not a boolean.
  
## Workaround (if any): 
Write fix and unit test :(
Getting master video promise status (vs currenttime) returns a big data object containing data such as current time and paused status as values.
https://github.com/polimediaupv/paella/blob/c5809367e0a66db1715c60ddf1962dcdbe86981b/plugins/es.upv.paella.usertracking.elasticsearchSaverPlugin/elasticsearchSaverPlugin.js#L26-L27

**Comment by ferserc1** [comment]
Fixed in branches 5.2, master and release/6.0.0
