### ISSUE TITLE
Slides and OCR of trimmed end of a video are visible using the OCR search.

### ISSUE THREAD

**Issue by iriadp** [polimediaupv/paella#359]
## Steps to reproduce:
1. Access a video with slides, OCR and trimmed end.
2. Search a word included in a slide outside the trimmed part of the video.
3. Check the results of the search.
 
## Actual Behavior:
 The "trimmed" slide will be visible and we can click on that slide and it will take us to the end of the video (that part of the video is not available to the public as it is trimmed).
 
## Expected Behavior:
 All the slides and OCR of trimmed parts of a video should not be accesible as results of any seach.

Reproduced it using Paella Player 5.3.9

**Comment by rubenrua** [comment]
See pull-request #281
