### ISSUE TITLE
Hide player controls if not used for n seconds

### ISSUE THREAD

**Issue by staubesv** [polimediaupv/paella#363]
## Actual Behavior:
The Paella player displays the player controls (everything that is not the video(s) itself) all the time. This becomes increasingly annoying with more and more controls being added (e.g. preview slide, next slide, cycle through video streams, swap video streams) which are not of relevance when just watching the video(s).
  
## Expected Behavior:
The Paella player should hide the player controls after few seconds of no user interaction and show them again as soon the user moves the mouse cursor after the player.
Alternatively, hiding could also occur when the mouse cursor leave the player area (or both).

This allows the user to focus on the video content and allows the player to use the maximum available screen estate for the content which is important when embedding the player.

#175 seems related to this feature request.

**Comment by karendolan** [comment]
@staubesv  Clients at our site have conflicting opinions on this. Some have request that player controls stay visible while the mouse is hovered over them, and only vanish when the mouse leaves the control bar area. With all the control bar options available, it might be frustrating for a user to have to keep wiggling the mouse in order to take them all in.

**Comment by staubesv** [comment]
@karendolan That would be addressed by the alternative solution where hiding only happens if the mouse cursor leaves the player. Note that we are not working on this, but we would consider it an improvement - in particular when embedding the player.

**Comment by miesgre** [comment]
@staubesv Paella hides the controls if the mouse does not move in a few seconds. The behavior is what Karen says. If the mouse stays in the controls bar, the controls bar does not hide. But if the mouse is outside the controls bar, it is hidden.

Check it the paella demos page: http://paellaplayer.upv.es/demo/player/index.html?id=belmar-demo
You can check it also in our media portal where paella is embeded: https://media.upv.es/#/portal/video/18fc41f0-a96e-11e5-80f5-152d229b83e3

**Comment by staubesv** [comment]
@miesgre Wow, wasn't aware of that ... ;-)

Note that it does not hide the zoom in/out buttons on the individual videos, though.

Anyway, I'm closing this issue. Thanks for clarifying!

**Comment by miesgre** [comment]
@staubesv It's true, the zoom in/out button does not hide. I didn't notice it.
Please, Fill an issue and @ferserc1 will take a look at that.

**Comment by staubesv** [comment]
@miesgre & @ferserc1 See #364
