### ISSUE TITLE
Zoom in/out button are not hidden when the mouse cursor leaves the player

### ISSUE THREAD

**Issue by staubesv** [polimediaupv/paella#364]
## Steps to reproduce:
1. Open Paella Player
2. Ensure that the mouse cursor is not over the player
3. Wait a few seconds
 
## Actual Behavior:
All player controls except the zoom in/out button are hidden
 
## Expected Behavior:
 All player controls should be hidden

## Workaround (if any):
Ignore

**Comment by miesgre** [comment]
Fixed in e08cda49b3c2b562904ae6c7c90f2b7d5273f84b
