### ISSUE TITLE
HLS Live multiple layout

### ISSUE THREAD

**Issue by kevin-og** [polimediaupv/paella#371]
Can someone please post a working data.json for HLS live w/ multiple (2) feeds to switch between from a user perspective?  I'm trying the below to no avail.  TIA!

{
        "metadata": {
                "duration": 887,
                "title": "HLS live streaming demo"
        },
        "streams": [
                {
                        "sources": {
                                "hls": [
                                        {
                                                "src": "https://TESTURL1/playlist.m3u8",
                        "mimetype": "video/mp4",
                        "isLiveStream": true
                    }
                ]
                        },
            "preview": "",
                        "content":"presenter"
                }
                {
                        "sources": {
                                "hls": [
                                        {
                                                "src": "https://TESTURL2/playlist.m3u8",
                        "mimetype": "video/mp4",
                        "isLiveStream": true
                    }
                ]
                        },
            "preview": "",
                        "content":"presenter"
                }
        ],
        "frameList": [
        ]
}

**Comment by karendolan** [comment]
Hi @kevin-og ,

I don't have a working sample, but want to point out that when the stream data is being procesesd, the following part of StreamProvider should have set "role":"master" to the first of the sources in that streams array.  The second sources would then be considered the secondary video. It might help to add a break point to that area in your browser debugger to verfiy the code is reached.
https://github.com/polimediaupv/paella/blob/abd5ef4b079346b5e67873945fb75a4ba11d5a11/src/04_video_container.js#L580-L599

Also, the JSON you posted is missing a comma between the 2 source objects. The browser debugger might alert you to issues in the input json.

**Comment by ferserc1** [comment]
From version 6 of Paella Player, you need to specify the content of the video. In the example you have proposed, you set the content "presenter" for the two streams.

You must to set different "content" values for each stream. The valid "content" values are defined in the config.json file, in the "video profile plugins" section. For dual stream videos, you can use one of these combinations:
- presenter, presentation
- presenter-2, presentation
- presenter-3, presentation

And, of course, you can define any other combination of values for the "content" parameter in the config.json file:
```
 "//**** Video profile plugins": "",
      ...
      "es.upv.paella.dualStreamProfilePlugin": { "enabled":true,
        "videoSets": [
          { "icon":"slide_professor_icon.svg", "id":"presenter_presentation", "content":["presenter","presentation"] },
          { "icon":"slide_professor_icon.svg", "id":"presenter2_presentation", "content":["presenter-2","presentation"] },
          { "icon":"slide_professor_icon.svg", "id":"presenter3_presentation", "content":["presenter-3","presentation"] }
        ]
      },
    ...
```

Please, for future reference, use the Paella Player mailing list. More info : [here](http://paellaplayer.upv.es/?page=contact)
