### ISSUE TITLE
Accessibility (general)

### ISSUE THREAD

**Issue by paulgration** [polimediaupv/paella#373]
It's not possible to access all features/menu items using just a keyboard and some items aren't described by screen readers.

There was an issue (#322) in Jan 2018 relating to accessibility of the of the volume slider and playback rate controls - the volume slider part was resolved in terms of controlling it via keyboard.

Items that I've noticed that aren't accessible from the keyboard when tabbing through items in the latest/current version (6.0.3) are:

Playback rate options
Zoom + and -
Video quality selection
Extended tab adaptor items
Search text field

I'm sure there are others to add to this list, I haven't tried all plugins..

There are _some_ controls that are accessible by the keyboard but not described by a screen readers (the sharing pop is an example of this, which has facebook, twitter and copy link options but none of these are described by screen readers).

The Paella player needs an audit of accessibility in general

**Comment by ferserc1** [comment]
From version 6.3.x you can activate the navigation with the tabulator key in the plugins where you are interested in the configuration file, using the `ariaLabel` attribute:

```
"es.upv.paella.fullScreenButtonPlugin": {"enabled":true, "reloadOnFullscreen":{ "enabled":true, "keepUserSelection":true }, "ariaLabel": "Switch full screen mode"},
```
