### ISSUE TITLE
JSON configuration formatting is not consistent

### ISSUE THREAD

**Issue by staubesv** [polimediaupv/paella#374]
The JSON configuration file of the Paella player has many incorrect formattings. The goal of this task (it is neither a feature nor a bug) is to use a JSON formatter to get consistently formatted json. 
I will use https://jsonformatter.org for this.

Also, the configuration file is working around the fact that JSON does not support comments. Most of the comments seem useless (how to disable/enable plugins is really obvious) or out-dated (e.g. reference to plugins.md on github which is a dead link).

It would be preferable to have the documentation separated and the individual plugins to be documented.

**Comment by lkiesow** [comment]
An idea for automatically checking the formatting as part of the Travis build:

```sh
% cat config.json | jq . > config.format.json
% diff -q config.format.json config.json
Files config.format.json and config.json differ
% echo $?
1     ← diff returns 1. Hence the build would fail since the files differ
```
