### ISSUE TITLE
Paella player plugins are not documented

### ISSUE THREAD

**Issue by staubesv** [polimediaupv/paella#377]
**Is your feature request related to a problem? Please describe.**
There is quite a bunch of plugins available for the Paella player. What is missing is a documentation that describes the individual plugins.

**Describe the solution you'd like**
There should be a documentation that describes each plugin individually including its configuration options.

**Comment by staubesv** [comment]
Ok, I see that there actually is a documentation for each plugin. At least I see the markdown files... haven't yet found them through the navigation on the github wiki ;-)

**Comment by miesgre** [comment]
The paella documentation is now online at https://paellaplayer.upv.es/docs/ (#378)
And a plugin list added to the navigation bar (https://paellaplayer.upv.es/docs/6.0.x/adopters/plugins.html).

Anyway we are working to improve the documentation (#376)
