### ISSUE TITLE
Use mkdocs for the documentation

### ISSUE THREAD

**Issue by staubesv** [polimediaupv/paella#378]
**Is your feature request related to a problem? Please describe.**
Doing the documentation on github seems quite a poor man's solution: Github tends to be quite overloaded with buttons etc. which are not relevant to the documentation.

**Describe the solution you'd like**
Include mkdocs.

**Comment by lkiesow** [comment]
Since you are on Github anyway, you could also use [Github pages](https://pages.github.com/) which is a bit simpler since it's already built into Github. It uses Jekyll for generating the pages.

**Comment by miesgre** [comment]
The paella documentation is now online at https://paellaplayer.upv.es/docs/
The documentation is built using `Jekyll`
