### ISSUE TITLE
Introduce "breaking changes" in changelog

### ISSUE THREAD

**Issue by staubesv** [polimediaupv/paella#379]
**Is your feature request related to a problem? Please describe.**
I'm just updating Paella from 5.x to 6.x. First time I open the player, things look weird...
Now, I've found that this is because of the format of data.json that seems to have changed.
No big deal, but I don't think that there is any information available on the fact that Adopters will need to adjust their integration when updating from 5.x to 6.x...

**Describe the solution you'd like**
Maybe just add a section "breaking changes" to each new version in the changelog in case there are breaking changes.

**Comment by karendolan** [comment]
Hi @staubesv, 
While it is fresh in your mind, can you describe that breaking data.json change? 
Yours gratefully,
Current 5x and Future 6x adopter :)

**Comment by staubesv** [comment]
@karendolan The introduction of multiple streams introduced the field 'content' for streams defined in config.json. Just adapted our integration to set this to 'presenter' or 'presentation' depending on the actual streams available and now 6.x works fine.

Note that the documentation on https://github.com/polimediaupv/paella/blob/develop/doc/adopter_doc/integrate_datajson.md is up-to-date (and generally quite a lot better than the last time I had a look at it).

So the breaking change is documented (but not as breaking change): https://github.com/polimediaupv/paella/commit/26dd78e446918f796a727051b313a41d23007a15#diff-6f9ae98469c069391dc65845bc3a1f20
