### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by stefanwifi** [polimediaupv/paella#380]
Hi,

I tried installing the paella player on my webserver. But I just can't get it to work:

http://test.koler.tv/index.html

I created a repositroy folder, changed the repository URL in the config file, made a copy of the youtube folder from the test_repository in my new repository folder and than edited the json within that folder (added two youtube IDs).

But there is nothing?! What am I doing wrong?

**Comment by ferserc1** [comment]
Please, use the Paella Player mailing list to ask installation and configuration questions:

https://listas.upv.es/mailman/listinfo/paellaplayer
