### ISSUE TITLE
Paella HLS Player: can't turn off automatic prefetching

### ISSUE THREAD

**Issue by miesgre** [polimediaupv/paella#384]
**NOTE**
Issue reported by Tim Schroeder at opencast jira [MH-13303](https://opencast.jira.com/browse/MH-13303)

**To Reproduce**
1. Use the Paella Player with HLS. 
2. Open a video page but don't click the play button. 

**Actual Behavior**
Up to 10min of the video gets buffered. 

**Expected behavior**
The video doesn't buffer until I click play. 

**Workaround (if any)**
Go into hls.min.js and change "maxMaxBufferLength" from 600 to e.g. 30. This way only up to 30s will be buffered. 

**Additional context**
We use Opencast in Moodle via the Plugins of [https://github.com/unirz-tu-ilmenau](https://github.com/unirz-tu-ilmenau) and in some courses several Videos are embedded on the course main page. So every time a student visits the course page the browser loads 10min of each video that's embedded there. This slows down our Moodle on these pages considerably. It also causes a lot of unnecessary traffic over mobile connections.

I tried setting autoStartLoad=false but then even the preview image and the play button don't load. That problem is described and solved here: [video-dev/hls.js/issues/824] But in order to use that solution I'd have to make my own Play button that triggers the actual video player. But that seems like an unnecessarily complicated workaround in order to prevent premature video buffering.

Thank you for contributing!

**Comment by ferserc1** [comment]
The configuration parameters of the HLS plugin are now exposed int he plugin configuration, at config.json:
```
"methods":[
      ... other video factory configurations
      {
        "factory":"HLSVideoFactory",
            "enabled":true,
            "config": {
                "*** You can add more hls.js settings here": "",
                "https://github.com/video-dev/hls.js/blob/master/docs/API.md": "",
                "maxMaxBufferLength": 30
            }
      },
```
