### ISSUE TITLE
gulp-traceur is deprecated/unmaintained

### ISSUE THREAD

**Issue by lkiesow** [polimediaupv/paella#387]
gulp-traceur is no longer maintained and should be replaced:

> Deprecated as Traceur is unmaintained. Check out [`gulp-babel`](https://github.com/babel/gulp-babel) instead.

https://www.npmjs.com/package/gulp-traceur

**Comment by miesgre** [comment]
Fixed in 6e0d6ac6caa377b6779bff984838b124951742a3
