### ISSUE TITLE
360 degree video does not load correctly the first time the page is opened

### ISSUE THREAD

**Issue by staubesv** [polimediaupv/paella#395]
**Describe the bug**
The first time a page containing the Paella Player supposed to display 360 degree video content is opened, the player does not start correctly.
Refreshing the page does solve the problem.

**To Reproduce**
1. Open https://paellaplayer.upv.es/demos/360-video/
2. Wait...

**Actual Behavior**
The player won't start correctly. In the browser console, a error message indicates a problem (see screenshot below)

**Expected behavior**
Player should start correctly.

**Workaround (if any)**
Reload the page.

**Screenshots**

![screen shot 2019-02-25 at 16 42 15](https://user-images.githubusercontent.com/1590263/53349163-c21c1a80-391c-11e9-8234-168ed80fa223.png)

I could reproduce this issue in Chrome and Safari (most recent versions) under MacOS X High Sierra.

**Comment by staubesv** [comment]
Note that there is a good chance that replacing loadDeps() as commented in #396 would fix this problem.

**Comment by ferserc1** [comment]
This issue is related to the prototype 360 video plugin, which was replaced by the canvas plugin system.
