### ISSUE TITLE
Switching between qualities does not work with Video360ThetaFactory factory

### ISSUE THREAD

**Issue by staubesv** [polimediaupv/paella#396]
**Describe the bug**
When using multiple qualities of the same 360° video, switching between those qualities does not work.

**To Reproduce**

1. Open Paella player with at least two different qualities of Ricoh Theta 360° video
2. Try to switch between the qualities

**Actual Behavior**
Switching between the different qualities does not work.

The browser console shows the following error message:

```
paella_player.js:1 Uncaught (in promise) ReferenceError: defer is not defined
    at paella_player.js:1
    at new Promise (<anonymous>)
    at e._loadDeps (paella_player.js:1)
    at paella_player.js:1
    at new Promise (<anonymous>)
    at e.load (paella_player.js:1)
    at paella_player.js:1
```

**Expected behavior**
Switching between the different qualities should work.

**Workaround (if any)**
Ignore and live with whatever quality the player has chosen.

**Comment by staubesv** [comment]
Replacing the function loadDeps in video360theta.js by

```
	_loadDeps() {
		return new Promise((resolve, reject) => {
			if (!window.$paella_bg2e) {
				require(['resources/deps/bg2e.js'], function(bg) {
					window.$paella_bg2e = bg;
					resolve(window.$paella_bg2e);
				});
			}
			else {
				resolve(window.$paella_bg2e);
			}	
		});
	}
```

does make quality switching work but it seems that the "old" quality is still played back (but not visible). 

This can be fixed by adding the lines ...

```
            if (this.canvasController && this.canvasController.video) {
              this.canvasController.video.pause();
            }
```

... to Video360Theta.load() before settings canvasControll to null.

What happens then is that after switching the quality for several times, the playback of the video gets low, likely because the library bg2e is still reacting on older instances (seems one more instance per quality switch is generated).

@ferserc1 As BG2E seems your baby, can you please point me to how I could correctly re-initialise the library when switching the quality?

**Comment by ferserc1** [comment]
This issue is related to the prototype 360 video plugin, which was replaced by the canvas plugin system.
