### ISSUE TITLE
Left-clicking video canvas to start/stop video playback does not work with 360° video

### ISSUE THREAD

**Issue by staubesv** [polimediaupv/paella#397]
**Describe the bug**
When using the Paella player to playback a 360° degree video (Video360Theta factory), left-clicking with the mouse over the video canvas doesn't cause the player to start/stop anymore.

**To Reproduce**
1. Go to https://paellaplayer.upv.es/demos/360-video/
2. Left-click on the video to start playback (works)
3. Left-click on the video to pause playback 

**Actual Behavior**
Left-clicking the video won't cause anything anymore.

**Expected behavior**
Independent of whether the Paella player plays back just normal video content or 360° video content, left-clicking on the video should always be usable to start/pause video playback.

**Additional notes**
When using two video track (one 360° video and one normal video), left-clicking behaviour is better. At the end of the day, the duration of the clicks would need to be track so that upon keyUp, start/pause is triggered for very short durations (and not triggered for longer durations)

**Comment by ferserc1** [comment]
This issue is related to the prototype 360 video plugin, which was replaced by the canvas plugin system.
