### ISSUE TITLE
360° video displayed in bad quality initially

### ISSUE THREAD

**Issue by staubesv** [polimediaupv/paella#398]
**Describe the bug**
Using a single quality 360° video, the video (even though approx. 2.5K pixels) is displayed in a very bad quality initially. Once the user changes size of the player window, the quality (of the same single quality 360° video) interestingly gets way better.

**To Reproduce**
1. Use a high quality 360° video
2. Open the Paella player
3. Look at the video
4. Change the size of the Paella player window
5. Look at the video again

**Actual Behavior**
The video quality in step 3 is way worse than later in step 5.

**Expected behavior**
The video quality in step 3 should be the same as in step 5

**Workaround (if any)**
Resize player

**Screenshots**
Initial quality:

![screen shot 2019-02-26 at 10 37 07](https://user-images.githubusercontent.com/1590263/53403057-30abb780-39b3-11e9-909c-758abe9b3327.png)

After changing the size of the player window:

![screen shot 2019-02-26 at 10 37 18](https://user-images.githubusercontent.com/1590263/53403085-4325f100-39b3-11e9-97e1-94fa70bb5ec3.png)

**Comment by ferserc1** [comment]
This issue is related to the prototype 360 video plugin, which was replaced by the canvas plugin system.
