### ISSUE TITLE
Remember volume

### ISSUE THREAD

**Issue by t-schroeder** [polimediaupv/paella#410]
**Is your feature request related to a problem? Please describe.**
The volume level set via the slider is not remembered when viewing another video on the same site.

**Describe the solution you'd like**
The volume level of the previously played video should be used when watching a new video.

**Describe alternatives you've considered**
Alternatively you have to either a) turn down the volume for each video you start watching or b) turn down the volume in some other way so you don't have to do it for each video separately.

**Additional context**
Using Paella Player 6.1.0 with Opencast 6.4. The video players on https://paellaplayer.upv.es/ behave the same way.

**Comment by ferserc1** [comment]
Implemented in 67db370a96aabf9a07be4cbba79d0944546a3cf6
