### ISSUE TITLE
Double click on embed/standard player should switch to full screen

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella#439]
Seems to be a standard with many players: 

https://youtu.be/--aYHgPKGIs

https://timms.uni-tuebingen.de/tp/UT_20180416_001_philheid_0001

https://www.videoportal.uni-freiburg.de/video/Die-postmigrantische-Gesellschaft-Dynamiken-zwischen-Akzeptanz-und-Abwehr-von-Diversitaet/fc7ed05b16b8d646be224343998c70b8

https://www.video.uni-erlangen.de/collection/clip/6/9859 (JW Player)

One click still pauses/plays the video.

**Comment by karendolan** [comment]
This looks like a less complex solution than most for keeping single click and adding double click action. 200ms is not too horrible a delay to add to the pause/play. : https://css-tricks.com/snippets/javascript/bind-different-events-to-click-and-double-click/
