### ISSUE TITLE
Player buttonOnScreen and click/touch play-pause Ok now on Mobile?

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella#440]
Hi, Do you have recommendation why the  play-pause action for the buttonOnScreen for Mobile is disabled? I'm about to test locally on iPhone (Safari) & Android (random browser) to see if it's functionally Ok to enable.
 
I'm wondering if there is a reason we would not want to enable the touch play-pause for play-button-on-screen?

**Comment by ferserc1** [comment]
The button is enabled in the develop branch, and I think it should also be enabled in the 6.3.x branch. I don't remember exactly why it was disabled at first, but actually I think it makes sense that it is enabled.

**Comment by karendolan** [comment]
thanks.
