### ISSUE TITLE
Why no volume button for mobile?

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella#442]
Why is the volume button disabled on mobile? Is it because the full screen view has the native volume and the Paella volume control doesn't get updates from it? Does it make sense to test the video object for volume when existing full screen? Is there another reason volume  button is not enabled for mobile?

Thanks!
Karen

**Comment by karendolan** [comment]
After testing a bit with volume enabled. I see that there is a lot of conflict between the native volume and the paella volume. I'm going to close this question for now, since it is not that critical.

**Comment by ferserc1** [comment]
I'm sorry I didn't answer before.

In iOS it is not possible to set the volume of the videos. According to Apple's official documentation on this topic:

> On iOS devices, the audio level is always under the user’s physical control. The volume property is not settable in JavaScript. Reading the volume property always returns 1.

[extracted from this link](https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html)

From the tests I've been able to do, something similar happens in Android, although I'm not sure it happens with all devices and versions.

I tested the iPadOS 13 beta on an iPad Pro this summer, and the behavior is somewhat different. It seems that iPadOS is not affected by these policies in the same way: for example, you can play several videos at the same time without having to mute them. However, the volume property  cannot be changed
