### ISSUE TITLE
AV1 codec support

### ISSUE THREAD

**Issue by markham89** [polimediaupv/paella#513]
Hi,
I would like Paella Player to support the AV1 codec.

Thx,

**Comment by turro** [comment]
Hi Markham

Paella uses the video codecs of the browser, so the codec will be used if the browser supports it

According to https://caniuse.com/#feat=av1 you will only be able to use it in recent versions of some desktop browsers (not mobile, not Safari). If you want to test, just write a data.json including that file as a source (better if it has .mp4 file extension)

Carlos


De: markham89 <notifications@github.com>
Enviado el: lunes, 17 de febrero de 2020 23:58
Para: polimediaupv/paella <paella@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [polimediaupv/paella] AV1 codec support (#513)


Hi,
I would like Paella Player to support the AV1 codec.

Thx,

**Comment by ferserc1** [comment]
Video codec support is browser and operating system dependent and cannot be implemented externally.
