### ISSUE TITLE
Request upgrade to latest HLS.js version (has lots of bug fixes)

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella#516]
# Is your feature request related to a problem? Please describe.
I'm frustrated when HLS videos don't play smoothly or freeze up  from weird buffer/stall problems when playing in Chrome and Firefox browsers.

# Describe the solution you'd like
I notice that the latest HLS.js release has a loooooot of bug fixes related to buffering issues and stall problems from even it's previous recent release. https://github.com/video-dev/hls.js/releases.

I suspect that the latest hls.js would make HLS video play smoother than the version currently residing in the UPV Paella HLS plugin dep folder.

**Comment by ferserc1** [comment]
The hlsjs library has been updated and is now installed via npm, in 300f43e
