### ISSUE TITLE
One stream as default in dual-stream

### ISSUE THREAD

**Issue by Jose96GIT** [polimediaupv/paella#517]
Hi all, I have a question about dual-stream? Is it possible to set one stream, as for example presenter stream, as the default one? So that the user starts with presenter stream and can change to presentation stream or both.

Thanks in advance.

**Comment by ferserc1** [comment]
You can use the "defaultProfile" attribute in the configuration file:

```
"defaultProfile":"presenter",
```

The profile identifiers are also in the same configuration file, in the plugins section, inside the `videoSet` section, the `id` attribute:

```
"plugins":{
    ...
    "list":{
        ...
      "es.upv.paella.singleStreamProfilePlugin": {
          "enabled": true,
          "videoSets": [
            { "icon":"professor_icon.svg", "id":"presenter", "content":["presenter"]},
            { "icon":"slide_icon.svg", "id":"presentation", "content":["presentation"]}
          ]
      },
      "es.upv.paella.dualStreamProfilePlugin": { "enabled":true,
        "videoSets": [
          { "icon":"slide_professor_icon.svg", "id":"presenter_presentation", "content":["presenter","presentation"] },
          { "icon":"slide_professor_icon.svg", "id":"presenter2_presentation", "content":["presenter-2","presentation"] },
          { "icon":"slide_professor_icon.svg", "id":"presenter3_presentation", "content":["presenter-3","presentation"] }
        ]
      },
```

Note that profiles selected by the user in the profile selector are saved as a preference, and the default profile is then ignored. To test the operation of the default profile, the 'lastProfile' cookie must be deleted.

**Comment by Jose96GIT** [comment]
It works, thanks a lot!
