### ISSUE TITLE
360° videos can't be played when using stream security

### ISSUE THREAD

**Issue by KatrinIhler** [polimediaupv/paella#535]
I've been investigating an issue with 360° videos for SWITCH. They use paella as a standalone player in version 6.3.2. Most importantly, they also use stream security, so their video URLs look like this:
`https://<download-node>/<video-path>/video.mp4?policy=<policy>&keyId=<keyId>&signature=<signature>`
And those parameters after the 'mp4' bit seem to be the problem. When you have those in the URL, the dependency _bg2e-es2015_ can't find the extension because the regular expression in the getExtension() method expects the extension to be the last part of the URL, which it's not. So isVideo() return false, which means the video can't be played. ("Error: No suitable plugin found for load")
This is probably also a problem for the integrated paella player in opencast if you use stream security.

This bug seems to be fixed in newer versions of bg2e by commit 56d4f1e4179a0cf97b6be55a353949ea06add9cf in versions >= 1.4.x.

I've already talked about his with @turro and we agreed that it would probably good to update bg2e to get rid of this.

**Comment by ferserc1** [comment]
I see the problem..

I can't update the graphics engine to version 1.4.x, because this version works only with PBR materials, and includes a brdf lookup texture embedded in the code that is quite heavy.

What I will do is apply the patch on the 1.3 branch to fix the problem, and then I'll update the dependency on paella player.

Thanks!

**Comment by KatrinIhler** [comment]
@ferserc1 Any idea when this might get fixed? :)

**Comment by ferserc1** [comment]
I would like to release a minor version with the problem solved this week
