### ISSUE TITLE
Play-Button should not overlay video while pausing. 

### ISSUE THREAD

**Issue by rrolf** [polimediaupv/paella#541]
While pausing the play/pause button is overlaying huge parts of the video, so that students cannot see anymore what was written below the button.

There is already a petition going on started by students of a german university:
https://www.reddit.com/r/KaIT/comments/g6j87e/petition_den_play_button_dezenter_gestalten/ 

while others found a workaround them selfs:
https://www.uni-osnabrueck.de/troubleshooters/?no_cache=1#c198470

**Comment by miesgre** [comment]
@rrolf You can disable the `es.upv.paella.playButtonOnScreenPlugin` plugin
https://github.com/polimediaupv/paella/blob/develop/config/config.json#L130

I think, It should work for you...

**Comment by ferserc1** [comment]
The plugin can now be set to not display when the video is paused:

```
"es.upv.paella.playButtonOnScreenPlugin": {"enabled":true, "showOnPause":false},
```
