### ISSUE TITLE
How store ocr slide content  to allow search text slide  with search toolbar button

### ISSUE THREAD

**Issue by markham89** [polimediaupv/paella#546]
Have a usage question?
======================
Hi,
i have ocr content of my slide,  how can store it (in repository) to activate search over this text.

thx,

**Comment by markham89** [comment]
thx

**Comment by miesgre** [comment]
Paella can't do that out of the box.

You will need to create a custom plugin to search in your ocr content.
You will need to implement a `SearchServicePlugIn ` plugin 
https://github.com/polimediaupv/paella/blob/0d3ff8f852159638795a922830c0aba7e003e5c3/src/06_2_search_service.js#L83-L90

and implement the search function.
You can find an example in the `opencast` project.
The opencast project has a plugin to search in the ocr texts os the slides. Sure you can do something similar.
https://github.com/opencast/opencast/blob/a515d816c2bb70b42b75307a41cf4cce2f9d40df/modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.searchPlugin/mh_search.js#L25-L81
