### ISSUE TITLE
PluginButton action() API broken

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella#570]
# Describe the bug

The Button plugin API's "action()" is broken for Plugin buttons off all types except type "actionButton".
https://github.com/polimediaupv/paella/blob/develop/doc/examples/button_plugin.md#execute-plugin-action

This change was made commit from Mar 16 2020:
https://github.com/polimediaupv/paella/commit/85781427d#diff-931028092ea1c6e6f0670a97e9599bf0L636-L651

# To Reproduce
1. Go to a custom plugin button that implements the action() API and is a PopUpButton and not an actionButton.
2. Click on the button
3. Notice that the showUI part executes but the action part was never called. The showUI cannot be substitute for click events because showUI might not be user initiated.

# Workaround (if any)
Revert to an older version of Paella player.

# Environment Information
 - OS: MacOS
 - Browser Chrome, Safari, FF
 - Browser Version latest
 - Paella version 6.4.3

# Additional context

Thank you for contributing!

**Comment by ferserc1** [comment]
Actually the action() API was only designed to work on action button type plugins, it probably worked on other types by accident. However, I find it an interesting feature to be able to intercept the action from other types of plugins.

**Comment by karendolan** [comment]
> Actually the action() API was only designed to work on action button type plugins, it probably worked on other types by accident. However, I find it an interesting feature to be able to intercept the action from other types of plugins.

I describe the pull as an API issue because the documentation does not reference button types when defining the PlugButton Action: https://github.com/polimediaupv/paella/blob/develop/doc/examples/button_plugin.md#execute-plugin-action.

We have a custom Popup PluginButton relies on the action() callback to distinguish between a user intentionally clicking the PluginButton as opposed the ShowUI being called programmatically, without a user click.

Restricting the action() to non-Pop PluginButton types reduces the richness of the PluginButton.
