### ISSUE TITLE
The "in" and "out" parameters of "Footprints" returned negative values

### ISSUE THREAD

**Issue by albacodina** [polimediaupv/paella#587]
# Describe the bug
Through a little script (https://github.com/migcm/PuMuKIT2-paella-player-bundle/pull/1/files), we retrieve the "in" and "out" parameters of "Footprints" and, without modification, send it to our server from time to time.
Checking the data, we have observed that, on some occasions, the “in” parameter and the “out” parameter are sent with a negative value. This only happens when a video/audio has been played from a device with Apple OS and Safari.

# Environment Information
 - OS: MacOS
 - Browser: Safari

**Comment by karendolan** [comment]
Our site also sees this in usertracking (Paella ~v5x).  I vaguely recall reading that a browser may return a random/unreliable currentTime when the video is not fully loaded. Maybe when toggling between resolutions?

To help normalize our data, with the knowledge that time 0  is a fallback currrent time, our site added the line below to the method linked below to prevent currentTime returning less than zero.

https://github.com/polimediaupv/paella/blob/develop/src/04_video_container.js#L1096-L1113
```
                                // Do not allow negative current time
                                if (time < 0) time = 0;
                                resolve(time)
```

It's possible that this could cause issues when multiple videos are being checked to be in synch and the main audio video returns a 0 time. Although, synching to 0 is less likely to cause player issues than synching to a negative time or a time greater than the duration. The line above does not protect against seeking to greater than duration. A video synch check in the middle of a video MacOS currentTime disconnect is unlikely but possible.
