### ISSUE TITLE
Layout Switch breaks the Presentation Stream during Dual Stream

### ISSUE THREAD

**Issue by cmmndr** [polimediaupv/paella#595]
# Describe the bug
When in a Dual Stream with the Paella Player, the Layout switch from Presentation + Speaker to solely the Speaker works fine.
Upon returning to the Presentation + Speaker Layout, the Presentation Stream breaks (see Screenshot below).
No Presentation Stream can be seen, yet the Speaker Stream is active nonetheless.

# To Reproduce
Bug occurs randomly and without any noticeable Pattern (Test Runs were between 0-30% Chance of Occuring)
1. Start Dual Stream
2. Switch Layout to Speaker
3. Switch Layout back to Presentation + Speaker

# Workaround (if any)
Reloading the Website resolves the temporary Problem but doesn't stop the Bug from happening again

# Environment Information
 - OS: Linux + Windows
 - Browser Firefox 79.0 + Chrome 84
 - Paella version: 6.4.3

# Additional context
I suspected the Layout Switch Function to not work properly but upon investigating, it turned out to be correct (which was also backed by the Fact that it works ~80% of the Time)

In the Screenshot you can see that, for some Reason, the display Tag and the opacity Tag didn't get restored to their expected values (meaning they stay hidden). If you manually correct them via the Developer Tools, the Presentation Stream becomes visible again but the it does not continue and is frozen instead.  

# Screenshots

![image](https://user-images.githubusercontent.com/6216007/90010771-bfdc8600-dca0-11ea-9ba3-d593fcdb35a3.png)

If this does not happen to be a Paella related Problem, i would be glad if someone could point me towards a potential Source of this Behaviour.

**Comment by ferserc1** [comment]
I have tested for several weeks on Windows, Linux and macOS, with the most widely used browsers (Chrome, Edge (chromium), Firefox, Safari, Opera) in the latest versions, and I have not been able to replicate the bug in any case.

It only occurs to me that there is some misconfiguration in the combination of the "content" attribute, in the video manifest streams, with the profile plugin settings in the "config.json" file:

[https://paellaplayer.upv.es/docs/6.4.x/adopters/integrate_datajson.html](https://paellaplayer.upv.es/docs/6.4.x/adopters/integrate_datajson.html)

I will continue to research the issue and expand the use cases, to see if I can replicate it.

**Comment by cmmndr** [comment]
Thanks for Testing @ferserc1 !
I kind of feared that this might be the case...
If you are willing to investigate the specific Setup that we run, we would be happy to give you credentials to look further into this phenomenon, so that you can watch this bug happen with your own eyes.

**Comment by karendolan** [comment]
Hi @cmmndr, our site occasionally experiences that "opacity:0% display:none" on the one video container after toggling profiles. The player has code to unhide the hidden container when it's toggled to display. The code might be caught in a race condition when conditions collide with other events. At least in our case. We notice it rarely on our publications. Do you have a public test video at your site where you see this?

**Comment by cmmndr** [comment]
Dear @karendolan . Thanks for your insight!

Here is the (half-)public test video where it is shown how the bug occurs: https://tud.link/ns03
The word to unlock the link is "paellaplayer" without quotation marks. Sorry for my grim face :)

The procedure is identical to the initial post; i change the layout and the second stream is not being reset to visible opacity/display values, as can be seen on the right side in the developer tools (greyed out div id="videoplayerwraper_1")

**Also, sorry if i haven't made this clear enough: this is a live stream from a live video conference**

**Comment by karendolan** [comment]
Hi @cmmndr,  

In the browser inspector/debugger window, go to source tab, look for the paella_player javascript file, search for text "class VideoWrapper extends paella.DomNode". In that class look for the method called "setVisible(visible,animate)".  Put a break point mark on the first conditional in the setVisible method. Then toggle the view profiles and watch the logic in that method.

The other place to look is the areas of "paella.addProfile(() => {".  In particular, I notice that some visibility lines are
```
"visible": "true",
```
and others are 
```
"visible": true,
```
It might not matter, but you could try changing them all one way or the other (with and without quotes) to see if that makes a difference in your browser or choice.

This is our version of the setVisible in VideoWrapper with extra debugging lines.
```
	setVisible(visible,animate) {
		// #HUDCE Debugging OPC-552 hidden videos on load & toggle
		base.log.debug(`HUDCE: PROFILE-1 setVisible '${this._identifier}' visible:${visible} animate:${animate}`);
		if (typeof(visible=="string")) {
			visible = /true/i.test(visible) ? true : false;
		}
		base.log.debug(`HUDCE: PROFILE-2 setVisible '${this._identifier}' visible:${visible} animate:${animate} dom:'${(this.domElement)}'`);
		if (visible && animate) {
			// #HUDCE OPC-552 animate opacity race condition with show, changed to fadeIn alone, submit to UPV
			$(this.domElement).fadeIn(300);
		}
		else if (visible && !animate) {
			$(this.domElement).show();
		}
		else if (!visible && animate) {
			// #DCE OPC-552, submit to UPV
			$(this.domElement).fadeOut(300);
		}
		else if (!visible && !animate) {
			$(this.domElement).hide();
		}
	}
```

**Comment by karendolan** [comment]
Some more thoughts for the checking the config.json.

1. If you are using fullscreen, try disabling reloadOnFullscreen

```
      "es.upv.paella.fullScreenButtonPlugin": {
        "enabled": true,
        "reloadOnFullscreen": {
          "//": "#HUDCE reloading video on full screen is problematic with rtmp live streams",
          "enabled": false,
```

2. Are your stream tracks in the mediapackage (data json) called "presenter" and "presentation"?
```
      "//**** Video profile plugins": "",
      "es.upv.paella.singleStreamProfilePlugin": {
          "enabled": true,
          "videoSets": [
            { "icon":"professor_icon.svg", "id":"presenter", "content":["presenter"]},
            { "icon":"slide_icon.svg", "id":"presentation", "content":["presentation"]}
          ]
      },
```

**Comment by cmmndr** [comment]
Dear @karendolan,
upon further investigation and following the leads you gave me i can state the following:

1. stream tracks are called "presenter" and "presentation", yes
2. Neither fullscreen nor non-fullscreen has changed the behaviour

While debugging with breakpoints i noticed something strange: obviously the setVisible() function is called twice, once for each stream or videowrapper, therefore two breakpoints per switch have been triggered. This went on for a good couple of times and then, the bug occurred and only **one single** breakpoints has been triggered, as if the bugged videowrapper-div did not call the function at all (or rather vice versa).
I also create a Breakpoint on DOM modification which showed that upon bug-occurring, the videowrapper is not touched at all so no halt on breakpoint during the occurrence...

So the current track i'm following is why setVisible() is not being called on the second videowrapper.
 
Also a note: this behaviour happens super inconsistently (like 1-3/10 times), which would support the race condition hypothesis but also the speed of execution had subjectively no impact on the probability of occurrence :/

**Comment by karendolan** [comment]
> So the current track i'm following is why setVisible() is not being called on the second videowrapper.
> 
> Also a note: this behaviour happens super inconsistently (like 1-3/10 times), which would support the race condition hypothesis but also the speed of execution had subjectively no impact on the probability of occurrence :/

Try breaking higher up in the stack chain. Specifically, search for the following section and put a break point before the getVideoData promise and after it (inside the then()). It's in that promise resolution that the setVisible() is called on the individual video.
```
        this.streamProvider.videoStreams.forEach((streamData,index) => {
            let profile = getProfile(streamData.content);
            let player = this.streamProvider.videoPlayers[index];       <---BREAK here: Verify this is called twice (index 0 and 1)
            let videoWrapper = this.videoWrappers[index];
            // #DCE debug log line
            base.log.debug(`PROFILE: checking video '${streamData.content}', player '${player._stream.content}', profile: '${JSON.stringify(profile)}'`);
            if (profile) {           <------   This profile should exist for each index
                player.getVideoData()   <------   This promise is a possible source of the race condition
                    .then((data) => {            
                        applyVideoRect(profile,data,videoWrapper,player);   <---BREAK here: Verify this is called twice (once per video)
                    });
            }
```

If you see 2 calls on the first break, but only 1 on the second break, try adding a *.catch()* with a log in the promise chain.
Something like:
```
                player.getVideoData()   <------   This promise is a possible source of the race condition
                    .then((data) => {            
                        applyVideoRect(profile,data,videoWrapper,player);   <---BREAK here: Verify this is called twice (once per video)
                    }).catch((err) => {    <--- maybe a deferred reject happened during getVideoData
                        base.log.debug(`PROFILE: Error before calling applyVideoRect during player.getVideoData(): ${err}`);
                    });
            }
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by karendolan** [comment]
Because getVideoData() is an asynch promise, it's possible that video index 1 executes its applyVideoRect() prior to video index 0. This occasional reverse execution order is another area to investigate.
