### ISSUE TITLE
Can you prevent loading profile from cookies?

### ISSUE THREAD

**Issue by theodortruffer** [polimediaupv/paella#652]
Hey there

Is there a way to prevent the player from loading the last used profile from the user's cookies? I would like to force the player to always load the default profile. 

Thanks!
Theo

**Comment by karendolan** [comment]
In theory, adding a URL param "&profile=<my favorite default profile to override cookie profile>" would have worked per [1], but there is an onresize() race-condition during load that overrides the URL param with the cookie value [2].

[1] https://github.com/polimediaupv/paella/blob/6.4.4/src/04_video_container.js#L1415-L1419
[2] https://github.com/polimediaupv/paella/blob/6.4.4/src/09_paella_player.js#L256-L269

**Comment by theodortruffer** [comment]
Ok, thanks for the quick answer! I'll try and look for another solution then.

**Comment by theodortruffer** [comment]
FYI, my solution for the problem: I simply reset the cookie before loading the player. The cookie is called 'lastProfile', so e.g. in PHP: `setcookie('lastProfile', null, -1);`
