### ISSUE TITLE
Keyboard support for rewind and fast-forward

### ISSUE THREAD

**Issue by gnarlex** [polimediaupv/paella#667]
# Is your feature request related to a problem? Please describe.
It's frustrating that there is no keyboard support for rewinding / fast-forwarding 30 seconds. People are used to pressing the left and right arrow keys to do this and it is implemented like this by many popular streaming services out there (YouTube, Netflix, Prime, etc). It greatly increases user experience to offer similar interfaces on all platforms.

# Describe the solution you'd like
* When I press the left arrow key on the keyboard the video rewinds X seconds.
* When I press the right arrow key on the keyboard the video forwards X seconds.

# Describe alternatives you've considered
Use the tab key to focus on the timeline input and use left and right arrow keys there.

**Comment by unikn-horstmann** [comment]
Hi Alexander,

for this purpose I added "plugins/es.upv.paella.keyPlugin/main.js":
...

else if (event.which==paella.Keys.J || event.which==paella.Keys.Left ) {
       this.jumpBackward();
       return true;
}
else if (event.which==paella.Keys.L || event.which==paella.Keys.Right ) {
       this.jumpForward();
       return true;
}

...

jumpBackward() {
	var videoContainer = paella.player.videoContainer;
	videoContainer.currentTime().then(function(currentTime) {
		paella.player.videoContainer.seekToTime(currentTime - 10);
	});
}

jumpForward() {
	var videoContainer = paella.player.videoContainer;
	videoContainer.currentTime().then(function(currentTime) {
		paella.player.videoContainer.seekToTime(currentTime + 10);
	});
}

May you can help me with my request:
Do you know how to increase and decrease the playback rate? I can hardcode it by using:
var videoContainer = paella.player.videoContainer;
videoContainer.setPlaybackRate(1.5);

But I would like to retrieve the current playbackrate (with playbackRate() which I assume is a get-method) but it did not work. Do you have an idea how I can resolve my problem?

Kind regards,
Matthias

**Comment by ferserc1** [comment]
You can implement your own key configuration using a KeyPlugin. The documentation is not updated on the web page, but there are documents available in the `doc` folder of the repository:

- [doc/developers/plugin_types.md](https://github.com/polimediaupv/paella/blob/develop/doc/developers/plugin_types.md)
- [doc/examples/key_plugin.md](https://github.com/polimediaupv/paella/blob/develop/doc/examples/key_plugin.md)
