### ISSUE TITLE
OS X Safari: Will stick with 360p when switching to full screen

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella#689]
With various versions of Safari videos will not change to 720p or 1080p when going full screen.

https://video.ethz.ch/speakers/lecture.html

**Comment by ferserc1** [comment]
Some Paella Player features require the execution of several sequential actions that are asynchronous in execution. In certain browsers, some of these actions cannot be performed if they are not triggered by a user action.

In the case of Safari, if the video quality is changed after enabling fullscreen, the result is that the video starts playing from the initial instant (does not continue from the previous position), so this behavior is blocked in this browser.

For this reason, multi quality video in mp4 format is not recommended, and it is preferable to offer it through HLS.
