### ISSUE TITLE
Play-Button starts the video just for a second

### ISSUE THREAD

**Issue by annasaxer** [polimediaupv/paella#693]
If you press the big Play-Button in the middle of the Video everything works fine at first. If you pause the video and restart it with the big Player-Button, the video starts for a second and stops again immediately. 
--> Screenshot is attached.

1. Go to 'https://paellaplayer.upv.es/demos/multi-quality-hls/ '
2. Click on the big Play-Button in the middle
3. Stop the video again
4. Press the Play-Button again.

# Workaround (if any)
If you press the small play-button in the left corner, or click somewhere else in the video, everything works correctly. 

# Environment Information
 - OS: Windows
 - Browser Chrome
 - Browser Version 89.0.4389.114 (Official Build) (64-Bit)
 - Paella version 6.5
 
![console](https://user-images.githubusercontent.com/47856295/113724481-afc35c00-96f2-11eb-99b6-287725c7beed.gif)

**Comment by ferserc1** [comment]
This issue is fixed in development branch and will be published in version 6.5.4
