### ISSUE TITLE
HLS OnDemand Playback

### ISSUE THREAD

**Issue by lwillmann** [polimediaupv/paella#716]
When I use the HLS Demo on a local build and click on the play button to start the playback, the video starts to buffer but not to play. I have to click on the button again, to actually start the video playback.

# Environment Information
 - OS: [Fedora 34]
 - Browser [Firefox]
 - Browser Version [88]
 - Paella version [6.5.4]

**Comment by ferserc1** [comment]
I have not been able to reproduce the failure.

In our experience, most of the time the problem with HLS is usually in the streaming server configuration, in the video encoding parameters or in the paella player configuration. Internally, Paella Player uses the hls.js library, you can consult the paella player and hls.js documentation for more information on HLS configuration.

In any case, I can't help you if you don't provide an example URL.

**Comment by lwillmann** [comment]
Thank you for the quick reply @ferserc1 actually I used the streaming URL provided in the examples. Please see the attached video file.




https://user-images.githubusercontent.com/52449143/117435688-6a32c280-af2e-11eb-88b9-b9e36e606b84.mp4
