### ISSUE TITLE
How do I know that the video is playing again?

### ISSUE THREAD

**Issue by albacodina** [polimediaupv/paella#751]
I need to know an event or parameter that indicates the play button was clicked again.

I am developing a functionality in my platform that plays a video before playing a paella video but when the paella video finishes, I want to click the play button and play again the introduction video and the paella video.

I have used _paella.events.endVideo_ and inside _paella.events.play_ but the problem is that when I use paella.events.play the intro video plays every time I click on the button.

Does anyone know how I can do this? Or is there any playlist functionality?

Thanks.

**Comment by karendolan** [comment]
Hi, 
I’m not a Paella player architect, but look at the usage of the “firstPlay” attribute in the PlayButtonOnScreen.
You can set a flag like that in your plugin to *true* on event paella.events.endVideo, then set it back to *false* after the next play event, after launching the intro video. On each play event, your code can reference its flag to see if it should load the intro or not.

Best of Luck,
Karen

**Comment by albacodina** [comment]
Thank you! I tried your option and it works the way I wanted.
