### ISSUE TITLE
Does the player support closed captions for live streams?

### ISSUE THREAD

**Issue by renefs** [polimediaupv/paella#770]
Since we are using Paella Player for live streamings, I was wondering if the player does support closed captions for HLS streams.

My guess is that it does not since the player requires a data.json with the stream configuration and it doesn't get anything directly from the HLS source, am I right?

Cheers,
Rene

**Comment by turro** [comment]
That is something we have considered several times, but we haven't implemented it. Do you have a source to test?

**Comment by renefs** [comment]
I'm afraid I don't have a reliable one currently 🙁 . Anyway, I think this feature would be very useful and we can have further discussions about its implementation (and our contribution to it).

**Comment by turro** [comment]
Agreed
