### ISSUE TITLE
Request for release of version 6.5.5, please?

### ISSUE THREAD

**Issue by reiferschris** [polimediaupv/paella#781]
Hi,
would you be so kind and cut a new release for version 6.5.5 which contains [this fix for hls streaming](https://github.com/polimediaupv/paella/commit/9134cc7870f3f570f8a06a8d7ca1cacfdfb250b2)?
We are currently facing this exact issue in the current release of the [ILIAS-Opencast plugin](https://github.com/fluxapps/OpenCast) which uses version 6.5.4.
We would be very grateful if you could release a new version!
Kind regards from cologne :)

**Comment by turro** [comment]
Hi @reiferschris. Today is holiday here :-) , so count with that for tomorrow

**Comment by reiferschris** [comment]
Thank you! Have a nice holiday ;)

**Comment by ferserc1** [comment]
6.5.5 version is released
