### ISSUE TITLE
Does the player support H265 ?

### ISSUE THREAD

**Issue by pubpy2015** [polimediaupv/paella#782]
Hi,
I am using your player to play a mp4 file stream. If video codec of mp4 file is H264 the player work fine.
But if video codec is H265 (record from H265 IP camera), the player can't play (black screen).
Is any config to play H265 stream ?

**Comment by ferserc1** [comment]
Hi

The video codecs supported by Paella Player (and in general, any HTML-based video player) depend on the browser and the platform where it is running. 

Although it is possible to implement support for new formats using media source extensions (such as HLS), the video encoding must be compatible with the browser.

For more information about video codec support in browsers, please visit the following link:

https://caniuse.com/?search=video

Fernando.

**Comment by pubpy2015** [comment]
Thanks,

I see it depends on the browser and almost all browsers cannot support H265 directly.
Seem there is a solution by using WebAssembly. 
https://github.com/sonysuqin/WasmVideoPlayer

can you support this ?

**Comment by turro** [comment]
I am sorry that we don't understand Chinese (i guess it is). Could you ellaborate a bit on what WasmVideoPlayer does?

**Comment by pubpy2015** [comment]
I don't understand Chinese too. But you can using Google Translate.
![ảnh](https://user-images.githubusercontent.com/59004953/138254975-8b1e1fc9-60c4-45c4-9e43-c2a5eea3019a.png)
here is other projects:
https://github.com/numberwolf/h265web.js
https://github.com/langhuihui/jessibuca

**Comment by ferserc1** [comment]
emscripten is a project that compiles C++ code into javascript executable in a browser. That is, this project relies on a module that runs ffmpeg and its dependencies directly in JavaScript. You don't need to be an expert to know that this is a terribly inefficient approach. That part alone is already an extremely heavy piece of software, and the rest of the project's modules only make the problem even worse.

Apart from this, which in itself is a reason not to include it in Paella Player, is the fact that it is only a matter of time before the different browsers support HEVC (h.265) natively, which means that in the medium term any effort we make to integrate this project will be useless.

Anyway, I have to remind that no new features are going to be included in Paella Player 6.x. For more information:
[Paella Player 7 presentation](https://github.com/polimediaupv/paella-core/blob/main/doc/paella_player_7_presentation.md)

If despite these problems you are still interested in having HEVC support out of the box, you can consult the [Paella Player 7 documentation](https://github.com/polimediaupv/paella-core/blob/main/doc/index.md), in particular, you would have to add two plugins of type [canvas](https://github.com/polimediaupv/paella-core/blob/main/doc/canvas_plugin.md) and [video format](https://github.com/polimediaupv/paella-core/blob/main/doc/video_plugin.md)

**Comment by pubpy2015** [comment]
Thanks,

I will try study from that.

**Comment by pubpy2015** [comment]
Agree with you the performance will be decreased when using WASM (CPU, GPU increase 2 times compared to Paella). But with a normal pc, i can play 16 video streams at 640x480 resolution on a web page. (https://github.com/langhuihui/jessibuca)

I reopen this issue because it seems that other browsers (Chrome, FireFox) are not planning to support H265.

https://support.google.com/chrome/thread/127402264/does-google-chrome-support-hevc-h-265-codec?hl=en
https://www.reddit.com/r/jellyfin/comments/gxe5s3/hevc_playback_on_firefox_how_to_get_it_work/

![ảnh](https://user-images.githubusercontent.com/59004953/142097142-b79dc3a5-2656-4671-9ca0-67521891afa3.png)
![ảnh](https://user-images.githubusercontent.com/59004953/142097560-c57cdcf7-ad70-4e7f-8106-b0d07b8b851b.png)

**Comment by ferserc1** [comment]
I think I have given you enough reasons to justify that we are not going to integrate this or any new feature in Paella Player 6 because this version is closed. Please refer to the following document for more information about the new [Paella Player 7 version](https://github.com/polimediaupv/paella-core/blob/main/doc/paella_player_7_presentation.md).

In any case, I say you again that It is not the goal of Paella Player to support this kind of experimental features. Feel free to fork this repository and integrate your own plugin
