### ISSUE TITLE
Add dist directory with the built version of the code.

### ISSUE THREAD

**Issue by rubenrua** [polimediaupv/paella#92]
Helpful to use with [bower](http://bower.io/)

Like:
 * https://github.com/twbs/bootstrap/tree/v3.3.1/dist
 * https://github.com/jquery/jquery/tree/2.1.3/dist
 * https://github.com/angular/bower-angular

**Comment by miesgre** [comment]
Done!
You can do now `bower install paella`

https://github.com/polimediaupv/bower-paella
