### ISSUE TITLE
Videos are cropped in the video container

### ISSUE THREAD

**Issue by Buttyx** [polimediaupv/paella#94]
The videos are cropped in the video container (see the image below). A window resize allows to recenter the videos. It occurs with single and dual stream videos.
![screen shot 2015-01-06 at 08 10 52](https://cloud.githubusercontent.com/assets/468737/5625469/928d426a-957b-11e4-8780-44a46386dc80.png)

**Comment by sersanor** [comment]
I can't reproduce this bug. Tested on Windows 8 x64 with Chrome-39, Firefox-34 and IE-11.
 Can you post a sample URL?

**Comment by spiraleddy** [comment]
Xavier,

I saw this sort of thing in Paella 3 with Flash videos and a slow connection. There was a timing issue on correctly sizing the video container during video load. I don't know that is still an issue in Paella 4 since we have moved away from Flash. Are you using Flash videos?

Regards,
Karen Dolan

**Comment by Buttyx** [comment]
Thank you both for your answers,

I have this issue with Flash and HTML5 videos in Safari-8.0.2 and Chrome-39 on OS X Yosemite but not in Firefox. It should not be a connection issue as I'm testing it locally. 

@sersanor: I'll try to put it online during the week as it could be also useful for #95. I'll come back to you with an url when it'll be available online.

**Comment by flyapen** [comment]
We are seeing this issue also ( latest paella player for opencast 4.0.13) .

Tested it on chrome ( linux and windows ) and IE11 . Firefox seems to work ok.

**Comment by miesgre** [comment]
@flyapen Can you provide me a URL to test? I am unable to reproduce this.

Thanks!

**Comment by spiraleddy** [comment]
We're not using Flash anymore, but for what it's worth, what I recall is that Flash swf had a problem setting the _isReady to true (src/03_video_nodes.js) or was late in setting it because of a slow connection.

**Comment by flyapen** [comment]
I'm using the HTML5 player as well, but maybe it's somehow related

**Comment by miesgre** [comment]
There is a bug in paella extended
@flyapen I uploaded a a branch for test (fix/videocrop). Can you test if it is working for you?
If it works, I will merge this to master

**Comment by flyapen** [comment]
@miesgre Thanks, that fix worked. I've tried a number of recordings and I can't reproduce the bug with this new version of paella player installed
