### ISSUE TITLE
Echo in dual-stream video played with the flash component 

### ISSUE THREAD

**Issue by Buttyx** [polimediaupv/paella#95]
I configured the player to only use the audio stream from the first video in the configuration file:
```    
     "stream0Audio":true,
     "stream1Audio":false
```

But when the dual-stream videos are played with a flash component, both audio stream are audible creating an echo.

**Comment by miesgre** [comment]
We can not reproduce this issue.

**Comment by spiraleddy** [comment]
@Buttyx you may be using the Old paella audio config. The "stream0Audio" is an old param, the new ones are "audio": {"master"..."slave...}. See commit https://github.com/polimediaupv/paella/commit/02863509c2c27a457b7df5c33e96538f3e840de9#diff-4f38f797527d10d00be10f37b7e7e2ba

**Comment by Buttyx** [comment]
@spiraleddy & @miesgre: Thanks it seems to be fixed now. This issue was only related to an older version of Paella.
